// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<AgentRequest> dco_decode_StreamSink_agent_request_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<MxMessage> dco_decode_StreamSink_mx_message_Sse(dynamic raw);

  @protected
  RustStreamSink<MxVerifyEvent> dco_decode_StreamSink_mx_verify_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AgentRequest dco_decode_agent_request(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  KeyInfo dco_decode_key_info(dynamic raw);

  @protected
  List<KeyInfo> dco_decode_list_key_info(dynamic raw);

  @protected
  List<MxDeviceInfo> dco_decode_list_mx_device_info(dynamic raw);

  @protected
  List<MxEmojiInfo> dco_decode_list_mx_emoji_info(dynamic raw);

  @protected
  List<MxRoomInfo> dco_decode_list_mx_room_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MxDeviceInfo dco_decode_mx_device_info(dynamic raw);

  @protected
  MxEmojiInfo dco_decode_mx_emoji_info(dynamic raw);

  @protected
  MxMessage dco_decode_mx_message(dynamic raw);

  @protected
  MxRoomInfo dco_decode_mx_room_info(dynamic raw);

  @protected
  MxVerifyEvent dco_decode_mx_verify_event(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<AgentRequest> sse_decode_StreamSink_agent_request_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MxMessage> sse_decode_StreamSink_mx_message_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MxVerifyEvent> sse_decode_StreamSink_mx_verify_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AgentRequest sse_decode_agent_request(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  KeyInfo sse_decode_key_info(SseDeserializer deserializer);

  @protected
  List<KeyInfo> sse_decode_list_key_info(SseDeserializer deserializer);

  @protected
  List<MxDeviceInfo> sse_decode_list_mx_device_info(
    SseDeserializer deserializer,
  );

  @protected
  List<MxEmojiInfo> sse_decode_list_mx_emoji_info(SseDeserializer deserializer);

  @protected
  List<MxRoomInfo> sse_decode_list_mx_room_info(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MxDeviceInfo sse_decode_mx_device_info(SseDeserializer deserializer);

  @protected
  MxEmojiInfo sse_decode_mx_emoji_info(SseDeserializer deserializer);

  @protected
  MxMessage sse_decode_mx_message(SseDeserializer deserializer);

  @protected
  MxRoomInfo sse_decode_mx_room_info(SseDeserializer deserializer);

  @protected
  MxVerifyEvent sse_decode_mx_verify_event(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_agent_request_Sse(
    RustStreamSink<AgentRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_mx_message_Sse(
    RustStreamSink<MxMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_mx_verify_event_Sse(
    RustStreamSink<MxVerifyEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agent_request(AgentRequest self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_key_info(KeyInfo self, SseSerializer serializer);

  @protected
  void sse_encode_list_key_info(List<KeyInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_mx_device_info(
    List<MxDeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mx_emoji_info(
    List<MxEmojiInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mx_room_info(
    List<MxRoomInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mx_device_info(MxDeviceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_mx_emoji_info(MxEmojiInfo self, SseSerializer serializer);

  @protected
  void sse_encode_mx_message(MxMessage self, SseSerializer serializer);

  @protected
  void sse_encode_mx_room_info(MxRoomInfo self, SseSerializer serializer);

  @protected
  void sse_encode_mx_verify_event(MxVerifyEvent self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
