// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1150702717;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_p43',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<KeyInfo>> crateApiSimpleGenerateKey({
    required String uid,
    required String algo,
    String? passphrase,
  });

  Future<void> crateApiSimpleInitApp();

  Future<List<KeyInfo>> crateApiSimpleListKeys();

  Future<void> crateApiSimpleMxConfirmVerify({required bool confirmed});

  Future<String?> crateApiSimpleMxGetAgentRoom();

  Future<bool> crateApiSimpleMxIsLoggedIn();

  Future<MxRoomInfo> crateApiSimpleMxJoinRoom({required String room});

  Future<List<MxDeviceInfo>> crateApiSimpleMxListDevices();

  Future<List<MxRoomInfo>> crateApiSimpleMxListRooms();

  Stream<MxMessage> crateApiSimpleMxListen({required String roomId});

  Stream<AgentRequest> crateApiSimpleMxListenAgent({required String roomId});

  Future<void> crateApiSimpleMxLogin({
    required String homeserver,
    required String username,
    required String password,
  });

  Future<void> crateApiSimpleMxLogout();

  Future<void> crateApiSimpleMxRespondListKeys({
    required String roomId,
    required String requestId,
  });

  Future<bool> crateApiSimpleMxRestore();

  Future<void> crateApiSimpleMxSend({
    required String roomId,
    required String text,
  });

  Future<void> crateApiSimpleMxSetAgentRoom({required String roomId});

  Stream<MxVerifyEvent> crateApiSimpleMxStartVerify();

  Future<void> crateApiSimpleSetStoreDir({required String dir});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<KeyInfo>> crateApiSimpleGenerateKey({
    required String uid,
    required String algo,
    String? passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uid, serializer);
          sse_encode_String(algo, serializer);
          sse_encode_opt_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_key_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleGenerateKeyConstMeta,
        argValues: [uid, algo, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGenerateKeyConstMeta => const TaskConstMeta(
    debugName: "generate_key",
    argNames: ["uid", "algo", "passphrase"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<KeyInfo>> crateApiSimpleListKeys() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_key_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleListKeysConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleListKeysConstMeta =>
      const TaskConstMeta(debugName: "list_keys", argNames: []);

  @override
  Future<void> crateApiSimpleMxConfirmVerify({required bool confirmed}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(confirmed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxConfirmVerifyConstMeta,
        argValues: [confirmed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxConfirmVerifyConstMeta =>
      const TaskConstMeta(
        debugName: "mx_confirm_verify",
        argNames: ["confirmed"],
      );

  @override
  Future<String?> crateApiSimpleMxGetAgentRoom() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMxGetAgentRoomConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxGetAgentRoomConstMeta =>
      const TaskConstMeta(debugName: "mx_get_agent_room", argNames: []);

  @override
  Future<bool> crateApiSimpleMxIsLoggedIn() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMxIsLoggedInConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxIsLoggedInConstMeta =>
      const TaskConstMeta(debugName: "mx_is_logged_in", argNames: []);

  @override
  Future<MxRoomInfo> crateApiSimpleMxJoinRoom({required String room}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(room, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mx_room_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxJoinRoomConstMeta,
        argValues: [room],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxJoinRoomConstMeta =>
      const TaskConstMeta(debugName: "mx_join_room", argNames: ["room"]);

  @override
  Future<List<MxDeviceInfo>> crateApiSimpleMxListDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mx_device_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxListDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxListDevicesConstMeta =>
      const TaskConstMeta(debugName: "mx_list_devices", argNames: []);

  @override
  Future<List<MxRoomInfo>> crateApiSimpleMxListRooms() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mx_room_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxListRoomsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxListRoomsConstMeta =>
      const TaskConstMeta(debugName: "mx_list_rooms", argNames: []);

  @override
  Stream<MxMessage> crateApiSimpleMxListen({required String roomId}) {
    final sink = RustStreamSink<MxMessage>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(roomId, serializer);
            sse_encode_StreamSink_mx_message_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleMxListenConstMeta,
          argValues: [roomId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleMxListenConstMeta =>
      const TaskConstMeta(debugName: "mx_listen", argNames: ["roomId", "sink"]);

  @override
  Stream<AgentRequest> crateApiSimpleMxListenAgent({required String roomId}) {
    final sink = RustStreamSink<AgentRequest>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(roomId, serializer);
            sse_encode_StreamSink_agent_request_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 11,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleMxListenAgentConstMeta,
          argValues: [roomId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleMxListenAgentConstMeta =>
      const TaskConstMeta(
        debugName: "mx_listen_agent",
        argNames: ["roomId", "sink"],
      );

  @override
  Future<void> crateApiSimpleMxLogin({
    required String homeserver,
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(homeserver, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxLoginConstMeta,
        argValues: [homeserver, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxLoginConstMeta => const TaskConstMeta(
    debugName: "mx_login",
    argNames: ["homeserver", "username", "password"],
  );

  @override
  Future<void> crateApiSimpleMxLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxLogoutConstMeta =>
      const TaskConstMeta(debugName: "mx_logout", argNames: []);

  @override
  Future<void> crateApiSimpleMxRespondListKeys({
    required String roomId,
    required String requestId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(requestId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxRespondListKeysConstMeta,
        argValues: [roomId, requestId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxRespondListKeysConstMeta =>
      const TaskConstMeta(
        debugName: "mx_respond_list_keys",
        argNames: ["roomId", "requestId"],
      );

  @override
  Future<bool> crateApiSimpleMxRestore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxRestoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxRestoreConstMeta =>
      const TaskConstMeta(debugName: "mx_restore", argNames: []);

  @override
  Future<void> crateApiSimpleMxSend({
    required String roomId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxSendConstMeta,
        argValues: [roomId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxSendConstMeta =>
      const TaskConstMeta(debugName: "mx_send", argNames: ["roomId", "text"]);

  @override
  Future<void> crateApiSimpleMxSetAgentRoom({required String roomId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxSetAgentRoomConstMeta,
        argValues: [roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxSetAgentRoomConstMeta =>
      const TaskConstMeta(debugName: "mx_set_agent_room", argNames: ["roomId"]);

  @override
  Stream<MxVerifyEvent> crateApiSimpleMxStartVerify() {
    final sink = RustStreamSink<MxVerifyEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_mx_verify_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 18,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleMxStartVerifyConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleMxStartVerifyConstMeta =>
      const TaskConstMeta(debugName: "mx_start_verify", argNames: ["sink"]);

  @override
  Future<void> crateApiSimpleSetStoreDir({required String dir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleSetStoreDirConstMeta,
        argValues: [dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSetStoreDirConstMeta =>
      const TaskConstMeta(debugName: "set_store_dir", argNames: ["dir"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<AgentRequest> dco_decode_StreamSink_agent_request_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<MxMessage> dco_decode_StreamSink_mx_message_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<MxVerifyEvent> dco_decode_StreamSink_mx_verify_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentRequest dco_decode_agent_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AgentRequest_ListKeys(requestId: dco_decode_String(raw[1]));
      case 1:
        return AgentRequest_Sign(
          requestId: dco_decode_String(raw[1]),
          fingerprint: dco_decode_String(raw[2]),
          description: dco_decode_String(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  KeyInfo dco_decode_key_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return KeyInfo(
      fingerprint: dco_decode_String(arr[0]),
      uid: dco_decode_String(arr[1]),
      algo: dco_decode_String(arr[2]),
      hasSecret: dco_decode_bool(arr[3]),
    );
  }

  @protected
  List<KeyInfo> dco_decode_list_key_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_key_info).toList();
  }

  @protected
  List<MxDeviceInfo> dco_decode_list_mx_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mx_device_info).toList();
  }

  @protected
  List<MxEmojiInfo> dco_decode_list_mx_emoji_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mx_emoji_info).toList();
  }

  @protected
  List<MxRoomInfo> dco_decode_list_mx_room_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mx_room_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MxDeviceInfo dco_decode_mx_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MxDeviceInfo(
      deviceId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      isCurrent: dco_decode_bool(arr[2]),
    );
  }

  @protected
  MxEmojiInfo dco_decode_mx_emoji_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MxEmojiInfo(
      symbol: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
    );
  }

  @protected
  MxMessage dco_decode_mx_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MxMessage(
      sender: dco_decode_String(arr[0]),
      body: dco_decode_String(arr[1]),
    );
  }

  @protected
  MxRoomInfo dco_decode_mx_room_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MxRoomInfo(
      roomId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      isEncrypted: dco_decode_bool(arr[2]),
    );
  }

  @protected
  MxVerifyEvent dco_decode_mx_verify_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MxVerifyEvent_Waiting();
      case 1:
        return MxVerifyEvent_RequestReceived();
      case 2:
        return MxVerifyEvent_Emojis(
          emojis: dco_decode_list_mx_emoji_info(raw[1]),
        );
      case 3:
        return MxVerifyEvent_Done();
      case 4:
        return MxVerifyEvent_Cancelled(reason: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<AgentRequest> sse_decode_StreamSink_agent_request_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<MxMessage> sse_decode_StreamSink_mx_message_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<MxVerifyEvent> sse_decode_StreamSink_mx_verify_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentRequest sse_decode_agent_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_requestId = sse_decode_String(deserializer);
        return AgentRequest_ListKeys(requestId: var_requestId);
      case 1:
        var var_requestId = sse_decode_String(deserializer);
        var var_fingerprint = sse_decode_String(deserializer);
        var var_description = sse_decode_String(deserializer);
        return AgentRequest_Sign(
          requestId: var_requestId,
          fingerprint: var_fingerprint,
          description: var_description,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  KeyInfo sse_decode_key_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fingerprint = sse_decode_String(deserializer);
    var var_uid = sse_decode_String(deserializer);
    var var_algo = sse_decode_String(deserializer);
    var var_hasSecret = sse_decode_bool(deserializer);
    return KeyInfo(
      fingerprint: var_fingerprint,
      uid: var_uid,
      algo: var_algo,
      hasSecret: var_hasSecret,
    );
  }

  @protected
  List<KeyInfo> sse_decode_list_key_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KeyInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_key_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<MxDeviceInfo> sse_decode_list_mx_device_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MxDeviceInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mx_device_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<MxEmojiInfo> sse_decode_list_mx_emoji_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MxEmojiInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mx_emoji_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<MxRoomInfo> sse_decode_list_mx_room_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MxRoomInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mx_room_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MxDeviceInfo sse_decode_mx_device_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_isCurrent = sse_decode_bool(deserializer);
    return MxDeviceInfo(
      deviceId: var_deviceId,
      displayName: var_displayName,
      isCurrent: var_isCurrent,
    );
  }

  @protected
  MxEmojiInfo sse_decode_mx_emoji_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_symbol = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    return MxEmojiInfo(symbol: var_symbol, description: var_description);
  }

  @protected
  MxMessage sse_decode_mx_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sender = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    return MxMessage(sender: var_sender, body: var_body);
  }

  @protected
  MxRoomInfo sse_decode_mx_room_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_roomId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_isEncrypted = sse_decode_bool(deserializer);
    return MxRoomInfo(
      roomId: var_roomId,
      name: var_name,
      isEncrypted: var_isEncrypted,
    );
  }

  @protected
  MxVerifyEvent sse_decode_mx_verify_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return MxVerifyEvent_Waiting();
      case 1:
        return MxVerifyEvent_RequestReceived();
      case 2:
        var var_emojis = sse_decode_list_mx_emoji_info(deserializer);
        return MxVerifyEvent_Emojis(emojis: var_emojis);
      case 3:
        return MxVerifyEvent_Done();
      case 4:
        var var_reason = sse_decode_String(deserializer);
        return MxVerifyEvent_Cancelled(reason: var_reason);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_agent_request_Sse(
    RustStreamSink<AgentRequest> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_agent_request,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_mx_message_Sse(
    RustStreamSink<MxMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_mx_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_mx_verify_event_Sse(
    RustStreamSink<MxVerifyEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_mx_verify_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_request(AgentRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AgentRequest_ListKeys(requestId: final requestId):
        sse_encode_i_32(0, serializer);
        sse_encode_String(requestId, serializer);
      case AgentRequest_Sign(
        requestId: final requestId,
        fingerprint: final fingerprint,
        description: final description,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(requestId, serializer);
        sse_encode_String(fingerprint, serializer);
        sse_encode_String(description, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_key_info(KeyInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fingerprint, serializer);
    sse_encode_String(self.uid, serializer);
    sse_encode_String(self.algo, serializer);
    sse_encode_bool(self.hasSecret, serializer);
  }

  @protected
  void sse_encode_list_key_info(List<KeyInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_key_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mx_device_info(
    List<MxDeviceInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mx_device_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mx_emoji_info(
    List<MxEmojiInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mx_emoji_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mx_room_info(
    List<MxRoomInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mx_room_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_mx_device_info(MxDeviceInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_bool(self.isCurrent, serializer);
  }

  @protected
  void sse_encode_mx_emoji_info(MxEmojiInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.symbol, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_mx_message(MxMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.body, serializer);
  }

  @protected
  void sse_encode_mx_room_info(MxRoomInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.roomId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isEncrypted, serializer);
  }

  @protected
  void sse_encode_mx_verify_event(
    MxVerifyEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MxVerifyEvent_Waiting():
        sse_encode_i_32(0, serializer);
      case MxVerifyEvent_RequestReceived():
        sse_encode_i_32(1, serializer);
      case MxVerifyEvent_Emojis(emojis: final emojis):
        sse_encode_i_32(2, serializer);
        sse_encode_list_mx_emoji_info(emojis, serializer);
      case MxVerifyEvent_Done():
        sse_encode_i_32(3, serializer);
      case MxVerifyEvent_Cancelled(reason: final reason):
        sse_encode_i_32(4, serializer);
        sse_encode_String(reason, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
