// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<AppMessage> dco_decode_StreamSink_app_message_Sse(dynamic raw);

  @protected
  RustStreamSink<MxMessage> dco_decode_StreamSink_mx_message_Sse(dynamic raw);

  @protected
  RustStreamSink<MxVerifyEvent> dco_decode_StreamSink_mx_verify_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AgentRequest dco_decode_agent_request(dynamic raw);

  @protected
  AppMessage dco_decode_app_message(dynamic raw);

  @protected
  AuthorityKeyExport dco_decode_authority_key_export(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AgentRequest dco_decode_box_autoadd_agent_request(dynamic raw);

  @protected
  BusCsrEvent dco_decode_box_autoadd_bus_csr_event(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  SshKeyDetails dco_decode_box_autoadd_ssh_key_details(dynamic raw);

  @protected
  BusCsrEvent dco_decode_bus_csr_event(dynamic raw);

  @protected
  BusOwnDevice dco_decode_bus_own_device(dynamic raw);

  @protected
  BusPeer dco_decode_bus_peer(dynamic raw);

  @protected
  ConnectedCardInfo dco_decode_connected_card_info(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeyInfo dco_decode_key_info(dynamic raw);

  @protected
  KeySealStatus dco_decode_key_seal_status(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BusOwnDevice> dco_decode_list_bus_own_device(dynamic raw);

  @protected
  List<BusPeer> dco_decode_list_bus_peer(dynamic raw);

  @protected
  List<ConnectedCardInfo> dco_decode_list_connected_card_info(dynamic raw);

  @protected
  List<KeyInfo> dco_decode_list_key_info(dynamic raw);

  @protected
  List<KeySealStatus> dco_decode_list_key_seal_status(dynamic raw);

  @protected
  List<MxDeviceInfo> dco_decode_list_mx_device_info(dynamic raw);

  @protected
  List<MxEmojiInfo> dco_decode_list_mx_emoji_info(dynamic raw);

  @protected
  List<MxRoomInfo> dco_decode_list_mx_room_info(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SubkeyInfo> dco_decode_list_subkey_info(dynamic raw);

  @protected
  MxDeviceInfo dco_decode_mx_device_info(dynamic raw);

  @protected
  MxEmojiInfo dco_decode_mx_emoji_info(dynamic raw);

  @protected
  MxMessage dco_decode_mx_message(dynamic raw);

  @protected
  MxRoomInfo dco_decode_mx_room_info(dynamic raw);

  @protected
  MxVerifyEvent dco_decode_mx_verify_event(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  SshKeyDetails? dco_decode_opt_box_autoadd_ssh_key_details(dynamic raw);

  @protected
  SshKeyDetails dco_decode_ssh_key_details(dynamic raw);

  @protected
  SubkeyInfo dco_decode_subkey_info(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<AppMessage> sse_decode_StreamSink_app_message_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MxMessage> sse_decode_StreamSink_mx_message_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<MxVerifyEvent> sse_decode_StreamSink_mx_verify_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AgentRequest sse_decode_agent_request(SseDeserializer deserializer);

  @protected
  AppMessage sse_decode_app_message(SseDeserializer deserializer);

  @protected
  AuthorityKeyExport sse_decode_authority_key_export(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AgentRequest sse_decode_box_autoadd_agent_request(
    SseDeserializer deserializer,
  );

  @protected
  BusCsrEvent sse_decode_box_autoadd_bus_csr_event(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SshKeyDetails sse_decode_box_autoadd_ssh_key_details(
    SseDeserializer deserializer,
  );

  @protected
  BusCsrEvent sse_decode_bus_csr_event(SseDeserializer deserializer);

  @protected
  BusOwnDevice sse_decode_bus_own_device(SseDeserializer deserializer);

  @protected
  BusPeer sse_decode_bus_peer(SseDeserializer deserializer);

  @protected
  ConnectedCardInfo sse_decode_connected_card_info(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeyInfo sse_decode_key_info(SseDeserializer deserializer);

  @protected
  KeySealStatus sse_decode_key_seal_status(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BusOwnDevice> sse_decode_list_bus_own_device(
    SseDeserializer deserializer,
  );

  @protected
  List<BusPeer> sse_decode_list_bus_peer(SseDeserializer deserializer);

  @protected
  List<ConnectedCardInfo> sse_decode_list_connected_card_info(
    SseDeserializer deserializer,
  );

  @protected
  List<KeyInfo> sse_decode_list_key_info(SseDeserializer deserializer);

  @protected
  List<KeySealStatus> sse_decode_list_key_seal_status(
    SseDeserializer deserializer,
  );

  @protected
  List<MxDeviceInfo> sse_decode_list_mx_device_info(
    SseDeserializer deserializer,
  );

  @protected
  List<MxEmojiInfo> sse_decode_list_mx_emoji_info(SseDeserializer deserializer);

  @protected
  List<MxRoomInfo> sse_decode_list_mx_room_info(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SubkeyInfo> sse_decode_list_subkey_info(SseDeserializer deserializer);

  @protected
  MxDeviceInfo sse_decode_mx_device_info(SseDeserializer deserializer);

  @protected
  MxEmojiInfo sse_decode_mx_emoji_info(SseDeserializer deserializer);

  @protected
  MxMessage sse_decode_mx_message(SseDeserializer deserializer);

  @protected
  MxRoomInfo sse_decode_mx_room_info(SseDeserializer deserializer);

  @protected
  MxVerifyEvent sse_decode_mx_verify_event(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  SshKeyDetails? sse_decode_opt_box_autoadd_ssh_key_details(
    SseDeserializer deserializer,
  );

  @protected
  SshKeyDetails sse_decode_ssh_key_details(SseDeserializer deserializer);

  @protected
  SubkeyInfo sse_decode_subkey_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_app_message_Sse(
    RustStreamSink<AppMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_mx_message_Sse(
    RustStreamSink<MxMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_mx_verify_event_Sse(
    RustStreamSink<MxVerifyEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_agent_request(AgentRequest self, SseSerializer serializer);

  @protected
  void sse_encode_app_message(AppMessage self, SseSerializer serializer);

  @protected
  void sse_encode_authority_key_export(
    AuthorityKeyExport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_agent_request(
    AgentRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bus_csr_event(
    BusCsrEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ssh_key_details(
    SshKeyDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bus_csr_event(BusCsrEvent self, SseSerializer serializer);

  @protected
  void sse_encode_bus_own_device(BusOwnDevice self, SseSerializer serializer);

  @protected
  void sse_encode_bus_peer(BusPeer self, SseSerializer serializer);

  @protected
  void sse_encode_connected_card_info(
    ConnectedCardInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_key_info(KeyInfo self, SseSerializer serializer);

  @protected
  void sse_encode_key_seal_status(KeySealStatus self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bus_own_device(
    List<BusOwnDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bus_peer(List<BusPeer> self, SseSerializer serializer);

  @protected
  void sse_encode_list_connected_card_info(
    List<ConnectedCardInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_key_info(List<KeyInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_key_seal_status(
    List<KeySealStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mx_device_info(
    List<MxDeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mx_emoji_info(
    List<MxEmojiInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mx_room_info(
    List<MxRoomInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_subkey_info(
    List<SubkeyInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mx_device_info(MxDeviceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_mx_emoji_info(MxEmojiInfo self, SseSerializer serializer);

  @protected
  void sse_encode_mx_message(MxMessage self, SseSerializer serializer);

  @protected
  void sse_encode_mx_room_info(MxRoomInfo self, SseSerializer serializer);

  @protected
  void sse_encode_mx_verify_event(MxVerifyEvent self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ssh_key_details(
    SshKeyDetails? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ssh_key_details(SshKeyDetails self, SseSerializer serializer);

  @protected
  void sse_encode_subkey_info(SubkeyInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
