// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -969657921;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_p43',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSimpleDeleteKey({required String fingerprint});

  Future<List<KeyInfo>> crateApiSimpleGenerateKey({
    required String uid,
    required String algo,
    String? passphrase,
  });

  Future<int> crateApiSimpleGetCardPinRetries({required String cardIdent});

  Future<String> crateApiSimpleGetPublicKeyArmored({
    required String fingerprint,
  });

  Future<String> crateApiSimpleGetPublicKeyOpenssh({
    required String fingerprint,
  });

  Future<SshKeyDetails?> crateApiSimpleGetSshKeyDetails({
    required String fingerprint,
  });

  Future<bool> crateApiSimpleHasCachedCardPin({required String cardIdent});

  Future<bool> crateApiSimpleHasCachedPassphrase({required String fingerprint});

  Future<List<KeyInfo>> crateApiSimpleImportCard({
    required String cardIdent,
    required String uid,
    required String pin,
  });

  Future<List<KeyInfo>> crateApiSimpleImportOpenpgpKey({
    required String armored,
  });

  Future<List<KeyInfo>> crateApiSimpleImportSshKey({
    required List<int> pemBytes,
    required String uidOverride,
    String? sshPassphrase,
    String? openpgpPassphrase,
  });

  Future<void> crateApiSimpleInitApp();

  Future<List<ConnectedCardInfo>> crateApiSimpleListConnectedCards();

  Future<List<KeyInfo>> crateApiSimpleListKeys();

  Future<void> crateApiSimpleMxClearCaches();

  Future<void> crateApiSimpleMxConfirmVerify({required bool confirmed});

  Future<String?> crateApiSimpleMxGetAgentRoom();

  Future<bool> crateApiSimpleMxIsLoggedIn();

  Future<MxRoomInfo> crateApiSimpleMxJoinRoom({required String room});

  Future<List<MxDeviceInfo>> crateApiSimpleMxListDevices();

  Future<List<MxRoomInfo>> crateApiSimpleMxListRooms();

  Stream<MxMessage> crateApiSimpleMxListen({required String roomId});

  Stream<AgentRequest> crateApiSimpleMxListenAgent({required String roomId});

  Future<void> crateApiSimpleMxLogin({
    required String homeserver,
    required String username,
    required String password,
  });

  Future<void> crateApiSimpleMxLogout();

  Future<void> crateApiSimpleMxRejectSign({
    required String roomId,
    required String requestId,
  });

  Future<void> crateApiSimpleMxRespondListKeys({
    required String roomId,
    required String requestId,
  });

  Future<void> crateApiSimpleMxRespondSign({
    required String roomId,
    required String requestId,
    required String passphrase,
  });

  Future<void> crateApiSimpleMxRespondSignCached({
    required String roomId,
    required String requestId,
  });

  Future<void> crateApiSimpleMxRespondSignCard({
    required String roomId,
    required String requestId,
    required String pin,
  });

  Future<void> crateApiSimpleMxRespondSignCardCached({
    required String roomId,
    required String requestId,
  });

  Future<bool> crateApiSimpleMxRestore();

  Future<void> crateApiSimpleMxSend({
    required String roomId,
    required String text,
  });

  Future<void> crateApiSimpleMxSetAgentRoom({required String roomId});

  Future<void> crateApiSimpleMxSetCacheKeyEnabled({required bool enabled});

  Stream<MxVerifyEvent> crateApiSimpleMxStartVerify();

  Future<void> crateApiSimpleRegisterCardIdent({
    required String fingerprint,
    required String cardIdent,
  });

  Future<void> crateApiSimpleSetKeyEnabled({
    required String fingerprint,
    required bool enabled,
  });

  Future<void> crateApiSimpleSetStoreDir({required String dir});

  Future<void> crateApiSimpleVerifyKeyPassphrase({
    required String fingerprint,
    required String passphrase,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSimpleDeleteKey({required String fingerprint}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fingerprint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleDeleteKeyConstMeta,
        argValues: [fingerprint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDeleteKeyConstMeta =>
      const TaskConstMeta(debugName: "delete_key", argNames: ["fingerprint"]);

  @override
  Future<List<KeyInfo>> crateApiSimpleGenerateKey({
    required String uid,
    required String algo,
    String? passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(uid, serializer);
          sse_encode_String(algo, serializer);
          sse_encode_opt_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_key_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleGenerateKeyConstMeta,
        argValues: [uid, algo, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGenerateKeyConstMeta => const TaskConstMeta(
    debugName: "generate_key",
    argNames: ["uid", "algo", "passphrase"],
  );

  @override
  Future<int> crateApiSimpleGetCardPinRetries({required String cardIdent}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cardIdent, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleGetCardPinRetriesConstMeta,
        argValues: [cardIdent],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetCardPinRetriesConstMeta =>
      const TaskConstMeta(
        debugName: "get_card_pin_retries",
        argNames: ["cardIdent"],
      );

  @override
  Future<String> crateApiSimpleGetPublicKeyArmored({
    required String fingerprint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fingerprint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleGetPublicKeyArmoredConstMeta,
        argValues: [fingerprint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetPublicKeyArmoredConstMeta =>
      const TaskConstMeta(
        debugName: "get_public_key_armored",
        argNames: ["fingerprint"],
      );

  @override
  Future<String> crateApiSimpleGetPublicKeyOpenssh({
    required String fingerprint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fingerprint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleGetPublicKeyOpensshConstMeta,
        argValues: [fingerprint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetPublicKeyOpensshConstMeta =>
      const TaskConstMeta(
        debugName: "get_public_key_openssh",
        argNames: ["fingerprint"],
      );

  @override
  Future<SshKeyDetails?> crateApiSimpleGetSshKeyDetails({
    required String fingerprint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fingerprint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_ssh_key_details,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetSshKeyDetailsConstMeta,
        argValues: [fingerprint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetSshKeyDetailsConstMeta =>
      const TaskConstMeta(
        debugName: "get_ssh_key_details",
        argNames: ["fingerprint"],
      );

  @override
  Future<bool> crateApiSimpleHasCachedCardPin({required String cardIdent}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cardIdent, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleHasCachedCardPinConstMeta,
        argValues: [cardIdent],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleHasCachedCardPinConstMeta =>
      const TaskConstMeta(
        debugName: "has_cached_card_pin",
        argNames: ["cardIdent"],
      );

  @override
  Future<bool> crateApiSimpleHasCachedPassphrase({
    required String fingerprint,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fingerprint, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleHasCachedPassphraseConstMeta,
        argValues: [fingerprint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleHasCachedPassphraseConstMeta =>
      const TaskConstMeta(
        debugName: "has_cached_passphrase",
        argNames: ["fingerprint"],
      );

  @override
  Future<List<KeyInfo>> crateApiSimpleImportCard({
    required String cardIdent,
    required String uid,
    required String pin,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(cardIdent, serializer);
          sse_encode_String(uid, serializer);
          sse_encode_String(pin, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_key_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleImportCardConstMeta,
        argValues: [cardIdent, uid, pin],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleImportCardConstMeta => const TaskConstMeta(
    debugName: "import_card",
    argNames: ["cardIdent", "uid", "pin"],
  );

  @override
  Future<List<KeyInfo>> crateApiSimpleImportOpenpgpKey({
    required String armored,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(armored, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_key_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleImportOpenpgpKeyConstMeta,
        argValues: [armored],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleImportOpenpgpKeyConstMeta =>
      const TaskConstMeta(
        debugName: "import_openpgp_key",
        argNames: ["armored"],
      );

  @override
  Future<List<KeyInfo>> crateApiSimpleImportSshKey({
    required List<int> pemBytes,
    required String uidOverride,
    String? sshPassphrase,
    String? openpgpPassphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pemBytes, serializer);
          sse_encode_String(uidOverride, serializer);
          sse_encode_opt_String(sshPassphrase, serializer);
          sse_encode_opt_String(openpgpPassphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_key_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleImportSshKeyConstMeta,
        argValues: [pemBytes, uidOverride, sshPassphrase, openpgpPassphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleImportSshKeyConstMeta => const TaskConstMeta(
    debugName: "import_ssh_key",
    argNames: ["pemBytes", "uidOverride", "sshPassphrase", "openpgpPassphrase"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<ConnectedCardInfo>> crateApiSimpleListConnectedCards() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_connected_card_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleListConnectedCardsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleListConnectedCardsConstMeta =>
      const TaskConstMeta(debugName: "list_connected_cards", argNames: []);

  @override
  Future<List<KeyInfo>> crateApiSimpleListKeys() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_key_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleListKeysConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleListKeysConstMeta =>
      const TaskConstMeta(debugName: "list_keys", argNames: []);

  @override
  Future<void> crateApiSimpleMxClearCaches() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMxClearCachesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxClearCachesConstMeta =>
      const TaskConstMeta(debugName: "mx_clear_caches", argNames: []);

  @override
  Future<void> crateApiSimpleMxConfirmVerify({required bool confirmed}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(confirmed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxConfirmVerifyConstMeta,
        argValues: [confirmed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxConfirmVerifyConstMeta =>
      const TaskConstMeta(
        debugName: "mx_confirm_verify",
        argNames: ["confirmed"],
      );

  @override
  Future<String?> crateApiSimpleMxGetAgentRoom() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMxGetAgentRoomConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxGetAgentRoomConstMeta =>
      const TaskConstMeta(debugName: "mx_get_agent_room", argNames: []);

  @override
  Future<bool> crateApiSimpleMxIsLoggedIn() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMxIsLoggedInConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxIsLoggedInConstMeta =>
      const TaskConstMeta(debugName: "mx_is_logged_in", argNames: []);

  @override
  Future<MxRoomInfo> crateApiSimpleMxJoinRoom({required String room}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(room, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_mx_room_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxJoinRoomConstMeta,
        argValues: [room],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxJoinRoomConstMeta =>
      const TaskConstMeta(debugName: "mx_join_room", argNames: ["room"]);

  @override
  Future<List<MxDeviceInfo>> crateApiSimpleMxListDevices() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mx_device_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxListDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxListDevicesConstMeta =>
      const TaskConstMeta(debugName: "mx_list_devices", argNames: []);

  @override
  Future<List<MxRoomInfo>> crateApiSimpleMxListRooms() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_mx_room_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxListRoomsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxListRoomsConstMeta =>
      const TaskConstMeta(debugName: "mx_list_rooms", argNames: []);

  @override
  Stream<MxMessage> crateApiSimpleMxListen({required String roomId}) {
    final sink = RustStreamSink<MxMessage>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(roomId, serializer);
            sse_encode_StreamSink_mx_message_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 22,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleMxListenConstMeta,
          argValues: [roomId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleMxListenConstMeta =>
      const TaskConstMeta(debugName: "mx_listen", argNames: ["roomId", "sink"]);

  @override
  Stream<AgentRequest> crateApiSimpleMxListenAgent({required String roomId}) {
    final sink = RustStreamSink<AgentRequest>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(roomId, serializer);
            sse_encode_StreamSink_agent_request_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 23,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleMxListenAgentConstMeta,
          argValues: [roomId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleMxListenAgentConstMeta =>
      const TaskConstMeta(
        debugName: "mx_listen_agent",
        argNames: ["roomId", "sink"],
      );

  @override
  Future<void> crateApiSimpleMxLogin({
    required String homeserver,
    required String username,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(homeserver, serializer);
          sse_encode_String(username, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxLoginConstMeta,
        argValues: [homeserver, username, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxLoginConstMeta => const TaskConstMeta(
    debugName: "mx_login",
    argNames: ["homeserver", "username", "password"],
  );

  @override
  Future<void> crateApiSimpleMxLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxLogoutConstMeta =>
      const TaskConstMeta(debugName: "mx_logout", argNames: []);

  @override
  Future<void> crateApiSimpleMxRejectSign({
    required String roomId,
    required String requestId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(requestId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxRejectSignConstMeta,
        argValues: [roomId, requestId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxRejectSignConstMeta => const TaskConstMeta(
    debugName: "mx_reject_sign",
    argNames: ["roomId", "requestId"],
  );

  @override
  Future<void> crateApiSimpleMxRespondListKeys({
    required String roomId,
    required String requestId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(requestId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxRespondListKeysConstMeta,
        argValues: [roomId, requestId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxRespondListKeysConstMeta =>
      const TaskConstMeta(
        debugName: "mx_respond_list_keys",
        argNames: ["roomId", "requestId"],
      );

  @override
  Future<void> crateApiSimpleMxRespondSign({
    required String roomId,
    required String requestId,
    required String passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(requestId, serializer);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxRespondSignConstMeta,
        argValues: [roomId, requestId, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxRespondSignConstMeta =>
      const TaskConstMeta(
        debugName: "mx_respond_sign",
        argNames: ["roomId", "requestId", "passphrase"],
      );

  @override
  Future<void> crateApiSimpleMxRespondSignCached({
    required String roomId,
    required String requestId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(requestId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxRespondSignCachedConstMeta,
        argValues: [roomId, requestId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxRespondSignCachedConstMeta =>
      const TaskConstMeta(
        debugName: "mx_respond_sign_cached",
        argNames: ["roomId", "requestId"],
      );

  @override
  Future<void> crateApiSimpleMxRespondSignCard({
    required String roomId,
    required String requestId,
    required String pin,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(requestId, serializer);
          sse_encode_String(pin, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxRespondSignCardConstMeta,
        argValues: [roomId, requestId, pin],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxRespondSignCardConstMeta =>
      const TaskConstMeta(
        debugName: "mx_respond_sign_card",
        argNames: ["roomId", "requestId", "pin"],
      );

  @override
  Future<void> crateApiSimpleMxRespondSignCardCached({
    required String roomId,
    required String requestId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(requestId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxRespondSignCardCachedConstMeta,
        argValues: [roomId, requestId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxRespondSignCardCachedConstMeta =>
      const TaskConstMeta(
        debugName: "mx_respond_sign_card_cached",
        argNames: ["roomId", "requestId"],
      );

  @override
  Future<bool> crateApiSimpleMxRestore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxRestoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxRestoreConstMeta =>
      const TaskConstMeta(debugName: "mx_restore", argNames: []);

  @override
  Future<void> crateApiSimpleMxSend({
    required String roomId,
    required String text,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          sse_encode_String(text, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxSendConstMeta,
        argValues: [roomId, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxSendConstMeta =>
      const TaskConstMeta(debugName: "mx_send", argNames: ["roomId", "text"]);

  @override
  Future<void> crateApiSimpleMxSetAgentRoom({required String roomId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(roomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleMxSetAgentRoomConstMeta,
        argValues: [roomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxSetAgentRoomConstMeta =>
      const TaskConstMeta(debugName: "mx_set_agent_room", argNames: ["roomId"]);

  @override
  Future<void> crateApiSimpleMxSetCacheKeyEnabled({required bool enabled}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMxSetCacheKeyEnabledConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMxSetCacheKeyEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "mx_set_cache_key_enabled",
        argNames: ["enabled"],
      );

  @override
  Stream<MxVerifyEvent> crateApiSimpleMxStartVerify() {
    final sink = RustStreamSink<MxVerifyEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_mx_verify_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 36,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSimpleMxStartVerifyConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSimpleMxStartVerifyConstMeta =>
      const TaskConstMeta(debugName: "mx_start_verify", argNames: ["sink"]);

  @override
  Future<void> crateApiSimpleRegisterCardIdent({
    required String fingerprint,
    required String cardIdent,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fingerprint, serializer);
          sse_encode_String(cardIdent, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleRegisterCardIdentConstMeta,
        argValues: [fingerprint, cardIdent],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRegisterCardIdentConstMeta =>
      const TaskConstMeta(
        debugName: "register_card_ident",
        argNames: ["fingerprint", "cardIdent"],
      );

  @override
  Future<void> crateApiSimpleSetKeyEnabled({
    required String fingerprint,
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fingerprint, serializer);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleSetKeyEnabledConstMeta,
        argValues: [fingerprint, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSetKeyEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_key_enabled",
        argNames: ["fingerprint", "enabled"],
      );

  @override
  Future<void> crateApiSimpleSetStoreDir({required String dir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleSetStoreDirConstMeta,
        argValues: [dir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSetStoreDirConstMeta =>
      const TaskConstMeta(debugName: "set_store_dir", argNames: ["dir"]);

  @override
  Future<void> crateApiSimpleVerifyKeyPassphrase({
    required String fingerprint,
    required String passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(fingerprint, serializer);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSimpleVerifyKeyPassphraseConstMeta,
        argValues: [fingerprint, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleVerifyKeyPassphraseConstMeta =>
      const TaskConstMeta(
        debugName: "verify_key_passphrase",
        argNames: ["fingerprint", "passphrase"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<AgentRequest> dco_decode_StreamSink_agent_request_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<MxMessage> dco_decode_StreamSink_mx_message_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<MxVerifyEvent> dco_decode_StreamSink_mx_verify_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentRequest dco_decode_agent_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return AgentRequest_ListKeys(requestId: dco_decode_String(raw[1]));
      case 1:
        return AgentRequest_Sign(
          requestId: dco_decode_String(raw[1]),
          fingerprint: dco_decode_String(raw[2]),
          description: dco_decode_String(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  SshKeyDetails dco_decode_box_autoadd_ssh_key_details(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ssh_key_details(raw);
  }

  @protected
  ConnectedCardInfo dco_decode_connected_card_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ConnectedCardInfo(
      ident: dco_decode_String(arr[0]),
      cardholderName: dco_decode_String(arr[1]),
      sigFingerprint: dco_decode_opt_String(arr[2]),
      authFingerprint: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  KeyInfo dco_decode_key_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return KeyInfo(
      fingerprint: dco_decode_String(arr[0]),
      uid: dco_decode_String(arr[1]),
      algo: dco_decode_String(arr[2]),
      hasSecret: dco_decode_bool(arr[3]),
      enabled: dco_decode_bool(arr[4]),
      cardIdents: dco_decode_list_String(arr[5]),
      subkeys: dco_decode_list_subkey_info(arr[6]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ConnectedCardInfo> dco_decode_list_connected_card_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_connected_card_info).toList();
  }

  @protected
  List<KeyInfo> dco_decode_list_key_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_key_info).toList();
  }

  @protected
  List<MxDeviceInfo> dco_decode_list_mx_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mx_device_info).toList();
  }

  @protected
  List<MxEmojiInfo> dco_decode_list_mx_emoji_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mx_emoji_info).toList();
  }

  @protected
  List<MxRoomInfo> dco_decode_list_mx_room_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_mx_room_info).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SubkeyInfo> dco_decode_list_subkey_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_subkey_info).toList();
  }

  @protected
  MxDeviceInfo dco_decode_mx_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MxDeviceInfo(
      deviceId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      isCurrent: dco_decode_bool(arr[2]),
    );
  }

  @protected
  MxEmojiInfo dco_decode_mx_emoji_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MxEmojiInfo(
      symbol: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
    );
  }

  @protected
  MxMessage dco_decode_mx_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MxMessage(
      sender: dco_decode_String(arr[0]),
      body: dco_decode_String(arr[1]),
    );
  }

  @protected
  MxRoomInfo dco_decode_mx_room_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return MxRoomInfo(
      roomId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      isEncrypted: dco_decode_bool(arr[2]),
    );
  }

  @protected
  MxVerifyEvent dco_decode_mx_verify_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MxVerifyEvent_Waiting();
      case 1:
        return MxVerifyEvent_RequestReceived();
      case 2:
        return MxVerifyEvent_Emojis(
          emojis: dco_decode_list_mx_emoji_info(raw[1]),
        );
      case 3:
        return MxVerifyEvent_Done();
      case 4:
        return MxVerifyEvent_Cancelled(reason: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SshKeyDetails? dco_decode_opt_box_autoadd_ssh_key_details(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_ssh_key_details(raw);
  }

  @protected
  SshKeyDetails dco_decode_ssh_key_details(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SshKeyDetails(
      name: dco_decode_String(arr[0]),
      algo: dco_decode_String(arr[1]),
      cardIdents: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  SubkeyInfo dco_decode_subkey_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SubkeyInfo(
      role: dco_decode_String(arr[0]),
      algo: dco_decode_String(arr[1]),
      opensshKey: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<AgentRequest> sse_decode_StreamSink_agent_request_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<MxMessage> sse_decode_StreamSink_mx_message_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<MxVerifyEvent> sse_decode_StreamSink_mx_verify_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentRequest sse_decode_agent_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_requestId = sse_decode_String(deserializer);
        return AgentRequest_ListKeys(requestId: var_requestId);
      case 1:
        var var_requestId = sse_decode_String(deserializer);
        var var_fingerprint = sse_decode_String(deserializer);
        var var_description = sse_decode_String(deserializer);
        return AgentRequest_Sign(
          requestId: var_requestId,
          fingerprint: var_fingerprint,
          description: var_description,
        );
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  SshKeyDetails sse_decode_box_autoadd_ssh_key_details(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ssh_key_details(deserializer));
  }

  @protected
  ConnectedCardInfo sse_decode_connected_card_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ident = sse_decode_String(deserializer);
    var var_cardholderName = sse_decode_String(deserializer);
    var var_sigFingerprint = sse_decode_opt_String(deserializer);
    var var_authFingerprint = sse_decode_opt_String(deserializer);
    return ConnectedCardInfo(
      ident: var_ident,
      cardholderName: var_cardholderName,
      sigFingerprint: var_sigFingerprint,
      authFingerprint: var_authFingerprint,
    );
  }

  @protected
  KeyInfo sse_decode_key_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fingerprint = sse_decode_String(deserializer);
    var var_uid = sse_decode_String(deserializer);
    var var_algo = sse_decode_String(deserializer);
    var var_hasSecret = sse_decode_bool(deserializer);
    var var_enabled = sse_decode_bool(deserializer);
    var var_cardIdents = sse_decode_list_String(deserializer);
    var var_subkeys = sse_decode_list_subkey_info(deserializer);
    return KeyInfo(
      fingerprint: var_fingerprint,
      uid: var_uid,
      algo: var_algo,
      hasSecret: var_hasSecret,
      enabled: var_enabled,
      cardIdents: var_cardIdents,
      subkeys: var_subkeys,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConnectedCardInfo> sse_decode_list_connected_card_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConnectedCardInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_connected_card_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<KeyInfo> sse_decode_list_key_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KeyInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_key_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<MxDeviceInfo> sse_decode_list_mx_device_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MxDeviceInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mx_device_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<MxEmojiInfo> sse_decode_list_mx_emoji_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MxEmojiInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mx_emoji_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<MxRoomInfo> sse_decode_list_mx_room_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MxRoomInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_mx_room_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SubkeyInfo> sse_decode_list_subkey_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SubkeyInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_subkey_info(deserializer));
    }
    return ans_;
  }

  @protected
  MxDeviceInfo sse_decode_mx_device_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_isCurrent = sse_decode_bool(deserializer);
    return MxDeviceInfo(
      deviceId: var_deviceId,
      displayName: var_displayName,
      isCurrent: var_isCurrent,
    );
  }

  @protected
  MxEmojiInfo sse_decode_mx_emoji_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_symbol = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    return MxEmojiInfo(symbol: var_symbol, description: var_description);
  }

  @protected
  MxMessage sse_decode_mx_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sender = sse_decode_String(deserializer);
    var var_body = sse_decode_String(deserializer);
    return MxMessage(sender: var_sender, body: var_body);
  }

  @protected
  MxRoomInfo sse_decode_mx_room_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_roomId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_isEncrypted = sse_decode_bool(deserializer);
    return MxRoomInfo(
      roomId: var_roomId,
      name: var_name,
      isEncrypted: var_isEncrypted,
    );
  }

  @protected
  MxVerifyEvent sse_decode_mx_verify_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return MxVerifyEvent_Waiting();
      case 1:
        return MxVerifyEvent_RequestReceived();
      case 2:
        var var_emojis = sse_decode_list_mx_emoji_info(deserializer);
        return MxVerifyEvent_Emojis(emojis: var_emojis);
      case 3:
        return MxVerifyEvent_Done();
      case 4:
        var var_reason = sse_decode_String(deserializer);
        return MxVerifyEvent_Cancelled(reason: var_reason);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SshKeyDetails? sse_decode_opt_box_autoadd_ssh_key_details(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ssh_key_details(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SshKeyDetails sse_decode_ssh_key_details(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_algo = sse_decode_String(deserializer);
    var var_cardIdents = sse_decode_list_String(deserializer);
    return SshKeyDetails(
      name: var_name,
      algo: var_algo,
      cardIdents: var_cardIdents,
    );
  }

  @protected
  SubkeyInfo sse_decode_subkey_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_role = sse_decode_String(deserializer);
    var var_algo = sse_decode_String(deserializer);
    var var_opensshKey = sse_decode_opt_String(deserializer);
    return SubkeyInfo(
      role: var_role,
      algo: var_algo,
      opensshKey: var_opensshKey,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_agent_request_Sse(
    RustStreamSink<AgentRequest> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_agent_request,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_mx_message_Sse(
    RustStreamSink<MxMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_mx_message,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_mx_verify_event_Sse(
    RustStreamSink<MxVerifyEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_mx_verify_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_request(AgentRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case AgentRequest_ListKeys(requestId: final requestId):
        sse_encode_i_32(0, serializer);
        sse_encode_String(requestId, serializer);
      case AgentRequest_Sign(
        requestId: final requestId,
        fingerprint: final fingerprint,
        description: final description,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(requestId, serializer);
        sse_encode_String(fingerprint, serializer);
        sse_encode_String(description, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ssh_key_details(
    SshKeyDetails self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ssh_key_details(self, serializer);
  }

  @protected
  void sse_encode_connected_card_info(
    ConnectedCardInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ident, serializer);
    sse_encode_String(self.cardholderName, serializer);
    sse_encode_opt_String(self.sigFingerprint, serializer);
    sse_encode_opt_String(self.authFingerprint, serializer);
  }

  @protected
  void sse_encode_key_info(KeyInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.fingerprint, serializer);
    sse_encode_String(self.uid, serializer);
    sse_encode_String(self.algo, serializer);
    sse_encode_bool(self.hasSecret, serializer);
    sse_encode_bool(self.enabled, serializer);
    sse_encode_list_String(self.cardIdents, serializer);
    sse_encode_list_subkey_info(self.subkeys, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_connected_card_info(
    List<ConnectedCardInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_connected_card_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_key_info(List<KeyInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_key_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mx_device_info(
    List<MxDeviceInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mx_device_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mx_emoji_info(
    List<MxEmojiInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mx_emoji_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_mx_room_info(
    List<MxRoomInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_mx_room_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_subkey_info(
    List<SubkeyInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_subkey_info(item, serializer);
    }
  }

  @protected
  void sse_encode_mx_device_info(MxDeviceInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_bool(self.isCurrent, serializer);
  }

  @protected
  void sse_encode_mx_emoji_info(MxEmojiInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.symbol, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_mx_message(MxMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sender, serializer);
    sse_encode_String(self.body, serializer);
  }

  @protected
  void sse_encode_mx_room_info(MxRoomInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.roomId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isEncrypted, serializer);
  }

  @protected
  void sse_encode_mx_verify_event(
    MxVerifyEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MxVerifyEvent_Waiting():
        sse_encode_i_32(0, serializer);
      case MxVerifyEvent_RequestReceived():
        sse_encode_i_32(1, serializer);
      case MxVerifyEvent_Emojis(emojis: final emojis):
        sse_encode_i_32(2, serializer);
        sse_encode_list_mx_emoji_info(emojis, serializer);
      case MxVerifyEvent_Done():
        sse_encode_i_32(3, serializer);
      case MxVerifyEvent_Cancelled(reason: final reason):
        sse_encode_i_32(4, serializer);
        sse_encode_String(reason, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ssh_key_details(
    SshKeyDetails? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ssh_key_details(self, serializer);
    }
  }

  @protected
  void sse_encode_ssh_key_details(
    SshKeyDetails self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.algo, serializer);
    sse_encode_list_String(self.cardIdents, serializer);
  }

  @protected
  void sse_encode_subkey_info(SubkeyInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.role, serializer);
    sse_encode_String(self.algo, serializer);
    sse_encode_opt_String(self.opensshKey, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
