//! Wire protocol for p43 messages sent through Matrix rooms.
//!
//! Every message serialises to a flat JSON object with a `"type"` discriminant,
//! e.g. `{ "type": "ssh.sign_request", "request_id": "…", … }`.
//!
//! TypeScript definitions are generated from these types via `typeshare-cli`:
//!
//! ```bash
//! typeshare lib/ --lang typescript --output-file ui/extension/src/generated/messages.ts
//! ```

use serde::{Deserialize, Serialize};
use typeshare::typeshare;

// ── Envelope ──────────────────────────────────────────────────────────────────

/// Every message crossing a Matrix room is one variant of this enum.
/// The `"type"` field is always present in the serialised JSON and can be
/// used for routing without deserialising the full payload.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum Message {
    // ── SSH agent ──────────────────────────────────────────────────────────
    #[serde(rename = "ssh.list_keys_request")]
    SshListKeysRequest(SshListKeysRequest),

    #[serde(rename = "ssh.list_keys_response")]
    SshListKeysResponse(SshListKeysResponse),

    #[serde(rename = "ssh.sign_request")]
    SshSignRequest(SshSignRequest),

    #[serde(rename = "ssh.sign_response")]
    SshSignResponse(SshSignResponse),

    // ── Shared ─────────────────────────────────────────────────────────────
    #[serde(rename = "error")]
    Error(ErrorResponse),
}

impl Message {
    /// The `"type"` string as it appears on the wire — useful for logging
    /// without a full match.
    pub fn type_name(&self) -> &'static str {
        match self {
            Self::SshListKeysRequest(_) => "ssh.list_keys_request",
            Self::SshListKeysResponse(_) => "ssh.list_keys_response",
            Self::SshSignRequest(_) => "ssh.sign_request",
            Self::SshSignResponse(_) => "ssh.sign_response",
            Self::Error(_) => "error",
        }
    }

    /// Serialise to a JSON string ready to be sent as a Matrix event body.
    pub fn to_json(&self) -> anyhow::Result<String> {
        Ok(serde_json::to_string(self)?)
    }

    /// Deserialise from a Matrix event body.
    pub fn from_json(s: &str) -> anyhow::Result<Self> {
        Ok(serde_json::from_str(s)?)
    }
}

// ── SSH agent types ───────────────────────────────────────────────────────────

/// Desktop → Phone: request the list of available signing keys.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SshListKeysRequest {
    /// UUID generated by the requester; echoed in the response for correlation.
    pub request_id: String,
}

/// Phone → Desktop: the list of available signing keys.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SshListKeysResponse {
    pub request_id: String,
    pub keys: Vec<SshKeyInfo>,
}

/// A single public key entry returned in [`SshListKeysResponse`].
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SshKeyInfo {
    /// SSH wire-format public key blob, base64-encoded.
    /// Matches what `SSH_AGENT_IDENTITIES_ANSWER` returns on the wire.
    pub public_key: String,
    /// SHA-256 fingerprint, e.g. `"SHA256:abc…"`.
    pub fingerprint: String,
    /// Human-readable label / comment stored alongside the key.
    pub comment: String,
}

/// Desktop → Phone: request a signature over `data` using the key
/// identified by `fingerprint`.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SshSignRequest {
    pub request_id: String,
    /// Must match a `fingerprint` from a prior [`SshListKeysResponse`].
    pub fingerprint: String,
    /// Raw bytes to sign, base64-encoded.
    pub data: String,
    /// SSH agent sign flags forwarded verbatim from the SSH client
    /// (0 = default, 2 = rsa-sha2-256, 4 = rsa-sha2-512).
    pub flags: u32,
    /// Shown on the phone's approval UI, e.g. `"git push on laptop"`.
    pub description: String,
}

/// Phone → Desktop: the resulting signature.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SshSignResponse {
    pub request_id: String,
    /// SSH wire-format signature blob, base64-encoded.
    pub signature: String,
}

// ── Shared ────────────────────────────────────────────────────────────────────

/// Sent by either side when a request cannot be fulfilled.
#[typeshare]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// Echoed from the triggering request, if one exists.
    pub request_id: Option<String>,
    pub message: String,
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip_sign_request() {
        let msg = Message::SshSignRequest(SshSignRequest {
            request_id: "550e8400-e29b-41d4-a716-446655440000".into(),
            fingerprint: "SHA256:abc123".into(),
            data: "SGVsbG8gd29ybGQ=".into(),
            flags: 0,
            description: "git push on laptop".into(),
        });

        let json = msg.to_json().unwrap();

        // type discriminant must be present and flat
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(v["type"], "ssh.sign_request");
        assert_eq!(v["request_id"], "550e8400-e29b-41d4-a716-446655440000");

        // must round-trip
        let back = Message::from_json(&json).unwrap();
        assert!(matches!(back, Message::SshSignRequest(_)));
    }

    #[test]
    fn round_trip_error() {
        let msg = Message::Error(ErrorResponse {
            request_id: Some("abc".into()),
            message: "User denied".into(),
        });
        let json = msg.to_json().unwrap();
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(v["type"], "error");
        assert_eq!(v["message"], "User denied");
    }
}
