// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `agent_state`, `authority_session`, `credential_cache`, `default_store_dir`, `ensure_registered_inprocess`, `external_tx_cell`, `forward`, `gate_key_dir`, `listener_stop_cell`, `locked_msg_queue`, `master_key`, `mx_store_dir`, `mx_verify_slot`, `open_gate_key_store`, `open_store`, `open_wallet`, `outbound_tx_cell`, `pending_list_keys`, `pending_signs`, `resolve_secret`, `run_in_process_agent`, `send_via_bridge`, `signing_key_cache`, `subkeys_for`, `to_key_info`, `tokio_rt`, `unlock_authority`, `wallet_ssh_public_keys`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `InProcessAgentState`, `InProcessSession`, `PendingListKeys`, `PendingSign`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `request_identities`, `sign`

/// Initialise tracing.
///
/// Pass an empty string for **local mode** (fmt output, zero network overhead).
/// Pass `"https://otel.adviser.com"` to export spans to the OTel Collector.
///
/// If the endpoint is unreachable the SDK retries silently and drops spans
/// after the retry budget — the app is never blocked.
///
/// Compiled as a no-op when the `p43` library is built without
/// `--features telemetry`.
Future<void> initTelemetry({required String endpoint}) =>
    RustLib.instance.api.crateApiSimpleInitTelemetry(endpoint: endpoint);

/// Shut down the OTel provider and flush all pending spans.
/// Call before the app exits.
Future<void> shutdownTelemetry() =>
    RustLib.instance.api.crateApiSimpleShutdownTelemetry();

/// Inject a W3C `traceparent` header for the current thread.
///
/// Dart should call this **immediately before** any FRB function that creates
/// a tracing span, then call [clearActiveTraceparent] once the call returns.
/// This stitches the Flutter span tree and the Rust span tree into a single
/// distributed trace in Jaeger.
///
/// The value must follow the W3C Trace Context format:
/// `00-<trace-id-32hex>-<parent-id-16hex>-<flags-2hex>`
Future<void> setActiveTraceparent({required String traceparent}) => RustLib
    .instance
    .api
    .crateApiSimpleSetActiveTraceparent(traceparent: traceparent);

/// Clear the stored traceparent for the current thread.
/// Call after every FRB call that was preceded by [setActiveTraceparent].
Future<void> clearActiveTraceparent() =>
    RustLib.instance.api.crateApiSimpleClearActiveTraceparent();

/// Must be called once from Dart before any key operation.
/// Pass `getApplicationSupportDirectory().path` (or equivalent).
Future<void> setStoreDir({required String dir}) =>
    RustLib.instance.api.crateApiSimpleSetStoreDir(dir: dir);

/// Signal the running Matrix listener to stop immediately.
///
/// Dart calls this from `didChangeAppLifecycleState(resumed)` so that messages
/// that arrived while the app was backgrounded are caught up on reconnect.
/// The listener tears down, the FRB stream fires `onDone`, and
/// `_scheduleReconnect` re-opens the connection with the last saved pointer.
Future<void> mxForceReconnect() =>
    RustLib.instance.api.crateApiSimpleMxForceReconnect();

/// Returns all keys in the local store (~/.config/project-43/keys).
Future<List<KeyInfo>> listKeys() =>
    RustLib.instance.api.crateApiSimpleListKeys();

/// Verify that `passphrase` correctly decrypts the secret key at `fingerprint`.
///
/// Returns `Ok(())` on success, or an error whose message can be shown to
/// the user (e.g. "Failed to decrypt secret keys — wrong passphrase?").
Future<void> verifyKeyPassphrase({
  required String fingerprint,
  required String passphrase,
}) => RustLib.instance.api.crateApiSimpleVerifyKeyPassphrase(
  fingerprint: fingerprint,
  passphrase: passphrase,
);

/// Delete a key (public + secret files + index entry) from the local store.
Future<void> deleteKey({required String fingerprint}) =>
    RustLib.instance.api.crateApiSimpleDeleteKey(fingerprint: fingerprint);

/// Enable or disable a key in the SSH agent.
///
/// Disabled keys are not advertised by `ssh-add -l` and cannot be used
/// for signing.  The key files are not modified.
Future<void> setKeyEnabled({
  required String fingerprint,
  required bool enabled,
}) => RustLib.instance.api.crateApiSimpleSetKeyEnabled(
  fingerprint: fingerprint,
  enabled: enabled,
);

/// Returns the armored OpenPGP public key for the given fingerprint.
Future<String> getPublicKeyArmored({required String fingerprint}) => RustLib
    .instance
    .api
    .crateApiSimpleGetPublicKeyArmored(fingerprint: fingerprint);

/// Returns the armored OpenPGP private key for `fingerprint`.
///
/// `passphrase` must match the key's stored passphrase (or be empty for
/// unencrypted keys).  Verification is performed before returning the armor so
/// that the caller knows the passphrase is correct before writing to disk.
Future<String> getPrivateKeyArmored({
  required String fingerprint,
  required String passphrase,
}) => RustLib.instance.api.crateApiSimpleGetPrivateKeyArmored(
  fingerprint: fingerprint,
  passphrase: passphrase,
);

/// Returns the OpenSSH `authorized_keys` line for the given fingerprint.
///
/// Uses the authentication subkey (falling back to the signing subkey).
Future<String> getPublicKeyOpenssh({required String fingerprint}) => RustLib
    .instance
    .api
    .crateApiSimpleGetPublicKeyOpenssh(fingerprint: fingerprint);

/// Resolve an SSH SHA-256 fingerprint (e.g. `SHA256:AbCd…`) to the key's
/// human-readable UID, algorithm, and associated card ident(s).
///
/// Returns `None` if no matching key is found.  Used by sign-request tiles and
/// the passphrase dialog to display key identity alongside the fingerprint.
Future<SshKeyDetails?> getSshKeyDetails({required String fingerprint}) =>
    RustLib.instance.api.crateApiSimpleGetSshKeyDetails(
      fingerprint: fingerprint,
    );

/// Generates a new soft key, saves it, and returns the updated key list.
/// `passphrase: None` skips encryption (not recommended).
Future<List<KeyInfo>> generateKey({
  required String uid,
  required String algo,
  String? passphrase,
}) => RustLib.instance.api.crateApiSimpleGenerateKey(
  uid: uid,
  algo: algo,
  passphrase: passphrase,
);

/// Return a summary of every connected OpenPGP card (no PIN required).
///
/// On macOS the system PC/SC daemon handles the transport; no additional
/// setup is needed.  Returns an empty list when no cards are present.
///
/// Not available on Android / iOS (no PC/SC subsystem) — returns an empty list.
Future<List<ConnectedCardInfo>> listConnectedCards() =>
    RustLib.instance.api.crateApiSimpleListConnectedCards();

/// Import a key from a connected OpenPGP card into the local key store.
///
/// Reads the signing-slot public key, uses the card to self-certify the UID
/// binding, saves `<fingerprint>.pub.asc` and `<fingerprint>.card.json`, and
/// returns the updated key list.
///
/// - `card_ident`: AID ident string from [list_connected_cards].
/// - `uid`: user ID string for the cert (e.g. `"Alice <alice@example.com>"`).
///   Pass the empty string to fall back to the cardholder name on the card.
/// - `pin`: card User Signing PIN (unlocks the SIG slot).
///
/// Not available on Android / iOS (no PC/SC subsystem).
Future<List<KeyInfo>> importCard({
  required String cardIdent,
  required String uid,
  required String pin,
}) => RustLib.instance.api.crateApiSimpleImportCard(
  cardIdent: cardIdent,
  uid: uid,
  pin: pin,
);

/// Import an OpenSSH private key file into the local key store as an OpenPGP
/// cert.
///
/// - `pem_bytes`: raw contents of the `id_ed25519` / `id_rsa` file.
/// - `uid_override`: UID string (e.g. `"Alice <alice@example.com>"`).  Pass the
///   empty string to derive from the SSH key's comment field.
/// - `ssh_passphrase`: passphrase that protects the SSH file itself (if any).
/// - `openpgp_passphrase`: passphrase to encrypt the stored OpenPGP secret key.
///   Pass `None` to store the key unencrypted (only do this on a secure device).
///
/// Returns the hex fingerprint of the newly imported cert and the updated key
/// list.
Future<List<KeyInfo>> importSshKey({
  required List<int> pemBytes,
  required String uidOverride,
  String? sshPassphrase,
  String? openpgpPassphrase,
}) => RustLib.instance.api.crateApiSimpleImportSshKey(
  pemBytes: pemBytes,
  uidOverride: uidOverride,
  sshPassphrase: sshPassphrase,
  openpgpPassphrase: openpgpPassphrase,
);

/// Import an armored OpenPGP private key (TSK) into the local key store.
///
/// `armored` is the full text of a `-----BEGIN PGP PRIVATE KEY BLOCK-----`
/// message.  The passphrase (if any) is not required at import time.
///
/// Returns the updated key list.
Future<List<KeyInfo>> importOpenpgpKey({required String armored}) =>
    RustLib.instance.api.crateApiSimpleImportOpenpgpKey(armored: armored);

/// Register a YubiKey (or other OpenPGP card) AID with a key entry.
///
/// Creates or updates `<fingerprint>.card.json` in the key store.  The same
/// key can be associated with multiple card AIDs — useful when a user has two
/// identical-content YubiKeys.
///
/// `card_ident` should be the AID string shown by `p43 key list --verbose`
/// or returned by `tx.application_identifier()?.ident()` in the card layer.
Future<void> registerCardIdent({
  required String fingerprint,
  required String cardIdent,
}) => RustLib.instance.api.crateApiSimpleRegisterCardIdent(
  fingerprint: fingerprint,
  cardIdent: cardIdent,
);

/// Password login.  Persists session under the app support directory.
Future<void> mxLogin({
  required String homeserver,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiSimpleMxLogin(
  homeserver: homeserver,
  username: username,
  password: password,
);

/// Restore a previously saved session.  Returns `true` if one was found.
/// Call at startup before showing the chat UI.
Future<bool> mxRestore() => RustLib.instance.api.crateApiSimpleMxRestore();

/// Logout and delete the local session.
Future<void> mxLogout() => RustLib.instance.api.crateApiSimpleMxLogout();

/// `true` if a Matrix session is currently active (non-blocking).
Future<bool> mxIsLoggedIn() =>
    RustLib.instance.api.crateApiSimpleMxIsLoggedIn();

Future<List<MxRoomInfo>> mxListRooms() =>
    RustLib.instance.api.crateApiSimpleMxListRooms();

Future<MxRoomInfo> mxJoinRoom({required String room}) =>
    RustLib.instance.api.crateApiSimpleMxJoinRoom(room: room);

Future<void> mxSend({required String roomId, required String text}) =>
    RustLib.instance.api.crateApiSimpleMxSend(roomId: roomId, text: text);

/// Stream all messages in `room_id` (history + live).
/// Dart receives each message as an `MxMessage` event.
Stream<MxMessage> mxListen({required String roomId}) =>
    RustLib.instance.api.crateApiSimpleMxListen(roomId: roomId);

/// Return the room ID saved as the agent room in matrix-config.json, if any.
Future<String?> mxGetAgentRoom() =>
    RustLib.instance.api.crateApiSimpleMxGetAgentRoom();

/// Persist `room_id` as the default agent room in matrix-config.json.
Future<void> mxSetAgentRoom({required String roomId}) =>
    RustLib.instance.api.crateApiSimpleMxSetAgentRoom(roomId: roomId);

/// Respond to an `ssh.list_keys_request` with wallet credentials.
///
/// Pass `master_hex` (the unlocked wallet master secret) to list keys from the
/// wallet (YubiKey auth-slot keys + stored SSH keys).  Pass `None` to fall back
/// to the legacy key store for backwards compatibility.
Future<void> mxRespondListKeys({
  required String roomId,
  required String requestId,
  String? masterHex,
}) => RustLib.instance.api.crateApiSimpleMxRespondListKeys(
  roomId: roomId,
  requestId: requestId,
  masterHex: masterHex,
);

/// Approve an `ssh.sign_request` using wallet credentials.
///
/// - `SshKey`    : in-memory sign, no dialog needed (private bytes already
///   decrypted by the wallet AES-GCM layer).
/// - `YubikeyRef`: opens the card, verifies the stored PIN, signs via the AUTH
///   slot — no PIN dialog needed.
Future<void> mxRespondSignWallet({
  required String roomId,
  required String requestId,
  required String masterHex,
}) => RustLib.instance.api.crateApiSimpleMxRespondSignWallet(
  roomId: roomId,
  requestId: requestId,
  masterHex: masterHex,
);

/// Subscribe to **all** p43 protocol messages in `room_id` with a single
/// Matrix sync loop.
///
/// Replaces the pair `mx_listen_agent` + `mx_listen_bus`.  The Flutter root
/// shell subscribes once here and fans out:
///   [`AppMessage::AgentEvent`] → `AgentScreen`
///   [`AppMessage::BusEvent`]   → `DevicesScreen`
///
/// Internally sets up the two-layer bus bridge:
///   - Raw Matrix messages → **external bus** (broadcast)
///   - Decrypt middleware → **internal bus** (broadcast, plaintext)
///   - Application dispatcher subscribes to internal bus → `AppMessage` stream
///   - **Outbound queue** (mpsc) → encrypt worker → Matrix send
///
/// The `agent_since` pointer (persisted in `matrix-config.json`) is respected
/// and updated on every sync batch so reconnects never replay seen messages.
Stream<AppMessage> mxListenAll({required String roomId}) =>
    RustLib.instance.api.crateApiSimpleMxListenAll(roomId: roomId);

/// Approve a device registration: verify the CSR, sign a cert with the
/// Approve a device CSR using the authority key already in `authority_session`.
///
/// Called when the wallet is unlocked — no credential prompt needed because
/// `wallet_unlock_session` already seated the authority key in memory.
Future<void> mxRespondCsrFromSession({
  required String roomId,
  required String requestId,
  required String csrB64,
  PlatformInt64? ttlSecs,
}) => RustLib.instance.api.crateApiSimpleMxRespondCsrFromSession(
  roomId: roomId,
  requestId: requestId,
  csrB64: csrB64,
  ttlSecs: ttlSecs,
);

/// authority key, and send `bus.cert_response` back into the room.
///
/// The authority key is unlocked using the card PIN (YubiKey) or passphrase
/// (soft key), following the same priority as other operations:
///   card=true  → PIN  (YK_PIN env or prompt)
///   card=false → passphrase (YK_PASSPHRASE env or prompt)
Future<void> mxRespondCsr({
  required String roomId,
  required String requestId,
  required String csrB64,
  PlatformInt64? ttlSecs,
  required bool useCard,
  String? fingerprint,
  String? pin,
  String? passphrase,
}) => RustLib.instance.api.crateApiSimpleMxRespondCsr(
  roomId: roomId,
  requestId: requestId,
  csrB64: csrB64,
  ttlSecs: ttlSecs,
  useCard: useCard,
  fingerprint: fingerprint,
  pin: pin,
  passphrase: passphrase,
);

/// Return the authority's public key bundle as a base64-encoded CBOR blob.
///
/// The returned string is suitable for embedding in a QR code and scanning
/// on a desktop device to bootstrap bus trust.  The format is:
///   `p43:bus:authority:<base64(CBOR AuthorityPub)>`
Future<String> busAuthorityPubQrData() =>
    RustLib.instance.api.crateApiSimpleBusAuthorityPubQrData();

/// Returns `true` when the bus authority has been initialised
/// (`authority.key.enc` exists in the bus directory).
Future<bool> busHasAuthority() =>
    RustLib.instance.api.crateApiSimpleBusHasAuthority();

/// Initialise the bus authority, sealing the encrypted key blob to **all**
/// currently-imported OpenPGP keys (card keys and soft keys alike).
///
/// This is a public-key-only operation — no passphrase or PIN is required.
/// Generate a new bus authority keypair and store it in the wallet.
///
/// Replaces `bus_init_authority` — no key-store recipients, no OpenPGP
/// encryption.  The gate-key AES-GCM is the sole protection layer.
///
/// Also writes `authority.pub.cbor` + `authority.cert.cbor` to disk so
/// running bus operations can still find them.
///
/// Returns the authority-pub CBOR as a hex string (used for the QR code).
Future<String> walletInitAuthority({required String masterHex}) => RustLib
    .instance
    .api
    .crateApiSimpleWalletInitAuthority(masterHex: masterHex);

/// Load the authority keypair from the wallet into the in-memory session.
///
/// Equivalent to `bus_unlock_session` but uses the wallet.
/// Call this whenever the wallet unlocks.
Future<void> walletUnlockSession({required String masterHex}) => RustLib
    .instance
    .api
    .crateApiSimpleWalletUnlockSession(masterHex: masterHex);

/// Check whether an authority key exists in the wallet.
Future<bool> walletHasAuthority({required String masterHex}) =>
    RustLib.instance.api.crateApiSimpleWalletHasAuthority(masterHex: masterHex);

/// Each imported key's `.pub.asc` file is used as a recipient.
///
/// Also writes `authority.pub.cbor` and a self-issued `authority.cert.cbor`.
Future<void> busInitAuthority() =>
    RustLib.instance.api.crateApiSimpleBusInitAuthority();

/// Return the sealing status of every keystore key against the current
/// `authority.key.enc`.  Returns an empty list when no authority exists.
Future<List<KeySealStatus>> busAuthorityKeySealStatus() =>
    RustLib.instance.api.crateApiSimpleBusAuthorityKeySealStatus();

/// Re-seal the authority key to **all** currently-imported keys.
///
/// The caller must supply credentials to unlock the existing authority:
/// - `use_card = true`:  unlock via connected YubiKey using `pin`.
/// - `use_card = false`: unlock via soft key at `unlock_fingerprint` using
///   `passphrase`.
Future<void> busResealAuthority({
  required bool useCard,
  String? unlockFingerprint,
  String? pin,
  String? passphrase,
}) => RustLib.instance.api.crateApiSimpleBusResealAuthority(
  useCard: useCard,
  unlockFingerprint: unlockFingerprint,
  pin: pin,
  passphrase: passphrase,
);

/// Re-seal the authority key to all keys **except** `exclude_fingerprint`.
///
/// Use this when a key has been compromised and must be revoked from authority
/// access.  At least one other sealed key must remain.
///
/// Credentials unlock the existing authority (use a key *other* than the one
/// being excluded).
Future<void> busResealAuthorityExcluding({
  required String excludeFingerprint,
  required bool useCard,
  String? unlockFingerprint,
  String? pin,
  String? passphrase,
}) => RustLib.instance.api.crateApiSimpleBusResealAuthorityExcluding(
  excludeFingerprint: excludeFingerprint,
  useCard: useCard,
  unlockFingerprint: unlockFingerprint,
  pin: pin,
  passphrase: passphrase,
);

/// Export the authority key bundle so it can be backed up or transferred.
///
/// Returns an error if the authority has not been initialised.
Future<AuthorityKeyExport> busExportAuthority() =>
    RustLib.instance.api.crateApiSimpleBusExportAuthority();

/// Import an authority key bundle (overwriting any existing authority files).
///
/// Use this to restore an authority from a backup or to move it to a new
/// device.  Both `key_enc` and `pub_cbor` must come from a prior
/// [`bus_export_authority`] call.
Future<void> busImportAuthority({
  required List<int> keyEnc,
  required List<int> pubCbor,
}) => RustLib.instance.api.crateApiSimpleBusImportAuthority(
  keyEnc: keyEnc,
  pubCbor: pubCbor,
);

/// Check whether any currently-imported keystore key can decrypt `key_enc`.
///
/// Returns the UIDs of all matching keys (could be more than one when the
/// blob was sealed to multiple recipients).  Returns an **error** if no
/// keystore key matches — the blob would be unrecoverable on this device.
///
/// Call this before writing the imported bundle to disk so users cannot
/// accidentally import a bundle that none of their keys can open.
Future<List<String>> busAuthorityCheckImportable({required List<int> keyEnc}) =>
    RustLib.instance.api.crateApiSimpleBusAuthorityCheckImportable(
      keyEnc: keyEnc,
    );

/// Return fingerprints of keystore keys whose encryption subkeys are **not**
/// listed as recipients in the current `authority.key.enc`.
///
/// Returns an empty `Vec` when no authority exists yet or all keys are sealed.
/// A non-empty return value means the Reseal tile should show a warning badge.
Future<List<String>> busAuthorityKeysNotSealed() =>
    RustLib.instance.api.crateApiSimpleBusAuthorityKeysNotSealed();

/// Unlock the bus authority session.
///
/// The authority key is decrypted from `authority.key.enc` and held in memory
/// until [`bus_lock_session`] or [`mx_clear_caches`] is called.  While unlocked
/// the app can decrypt incoming `BusSecure` messages and seal outgoing responses.
Future<void> busUnlockSession({
  required bool useCard,
  String? fingerprint,
  String? pin,
  String? passphrase,
}) => RustLib.instance.api.crateApiSimpleBusUnlockSession(
  useCard: useCard,
  fingerprint: fingerprint,
  pin: pin,
  passphrase: passphrase,
);

/// Clear the in-memory authority session key.
///
/// After this call the app can no longer decrypt `BusSecure` messages or seal
/// outgoing responses until [`bus_unlock_session`] is called again.
Future<void> busLockSession() =>
    RustLib.instance.api.crateApiSimpleBusLockSession();

/// Returns `true` if the authority session key is currently unlocked.
Future<bool> busIsSessionUnlocked() =>
    RustLib.instance.api.crateApiSimpleBusIsSessionUnlocked();

/// Returns `true` if cached credentials exist for the given SSH fingerprint,
/// meaning `mx_respond_sign_cached` can proceed without a passphrase dialog.
///
/// Returns `true` when any of:
/// - A passphrase is cached in the credential cache (slow KDF path).
/// - A decrypted Ed25519 keypair is cached (fast, microseconds).
/// - A decrypted RSA key is cached (fast, zero KDF).
///
/// Dart uses this to decide whether to auto-approve or show the dialog.
/// When biometric approval is added, this is also the gate for whether
/// biometric confirmation suffices or the user must type their passphrase.
Future<bool> hasCachedPassphrase({required String fingerprint}) => RustLib
    .instance
    .api
    .crateApiSimpleHasCachedPassphrase(fingerprint: fingerprint);

/// Prime the credential cache for a given key fingerprint.
///
/// `bus_unlock_session` already calls this internally; use this function when
/// you need to prime the cache from a path that bypasses `bus_unlock_session`.
Future<void> mxPrimePassphraseCache({
  required String fingerprint,
  required String passphrase,
}) => RustLib.instance.api.crateApiSimpleMxPrimePassphraseCache(
  fingerprint: fingerprint,
  passphrase: passphrase,
);

/// Enable or disable the in-memory signing-key cache.
///
/// When `enabled`:
/// - `mx_respond_sign` extracts and caches the decrypted Ed25519 keypair bytes
///   so subsequent `mx_respond_sign_cached` calls skip the KDF entirely.
///
/// When `disabled`:
/// - The signing-key cache is cleared immediately.
/// - `mx_respond_sign_cached` falls back to the passphrase cache + KDF.
///
/// Call at startup with the persisted setting value, and again whenever the
/// user toggles the setting.
Future<void> mxSetCacheKeyEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiSimpleMxSetCacheKeyEnabled(enabled: enabled);

/// Set the maximum age of Matrix messages the UI will process.
///
/// Messages with `origin_server_ts` older than `hours` before *now* are
/// silently dropped before they reach the bus pipeline.
/// Default is 8 h.  Pass 0 to disable the filter (accept all messages).
///
/// Call at startup with the persisted setting value, and again whenever the
/// user changes it in Settings.
Future<void> mxSetMessageMaxAgeHours({required BigInt hours}) =>
    RustLib.instance.api.crateApiSimpleMxSetMessageMaxAgeHours(hours: hours);

/// Update the credential cache timeout.
///
/// Pass the value of `AgentSettings.cacheTimeoutMinutes * 60` (converted to
/// seconds), or `0` to disable automatic expiry.
///
/// Call at startup and whenever the setting changes.
Future<void> credentialCacheSetTimeout({required BigInt timeoutSecs}) => RustLib
    .instance
    .api
    .crateApiSimpleCredentialCacheSetTimeout(timeoutSecs: timeoutSecs);

/// Lock the session and purge **all** in-memory credentials.
///
/// Clears:
/// - Credential cache (all PINs and passphrases)
/// - Derived signing-key cache (decrypted Ed25519 / RSA keypairs)
/// - Authority session key
///
/// Does **not** affect `KEY_CACHE_ENABLED` — caching resumes on the next
/// successful sign if still enabled.
///
/// Call from the global lock button and on screen-lock / app-background events.
Future<void> lockAll() => RustLib.instance.api.crateApiSimpleLockAll();

/// Clear all in-memory credential caches.
///
/// Delegates to [`lock_all`].  Kept for backwards compatibility.
Future<void> mxClearCaches() =>
    RustLib.instance.api.crateApiSimpleMxClearCaches();

/// Approve an `ssh.sign_request` using an explicitly supplied passphrase.
///
/// On success:
/// - The passphrase is stored in the in-memory cache (slow fallback path).
/// - If "cache decrypted key" is enabled, the decrypted Ed25519 keypair bytes
///   are also cached so subsequent auto-approve signs skip the KDF entirely.
Future<void> mxRespondSign({
  required String roomId,
  required String requestId,
  required String passphrase,
}) => RustLib.instance.api.crateApiSimpleMxRespondSign(
  roomId: roomId,
  requestId: requestId,
  passphrase: passphrase,
);

/// Approve an `ssh.sign_request` for a card-backed key using the card's User PIN.
///
/// The card's AUTH slot is used for signing (same slot the SSH agent uses).
/// The User PIN (typically 6+ digits on YubiKey) unlocks the AUTH slot — it
/// is NOT the Admin PIN or the Signing PIN.
///
/// On success the PIN is cached in memory keyed by card AID ident so that
/// `mx_respond_sign_card_cached` can skip the PIN dialog for subsequent requests.
///
/// Not available on Android / iOS (no PC/SC subsystem).
Future<void> mxRespondSignCard({
  required String roomId,
  required String requestId,
  required String pin,
}) => RustLib.instance.api.crateApiSimpleMxRespondSignCard(
  roomId: roomId,
  requestId: requestId,
  pin: pin,
);

/// Returns `true` if a cached PIN exists for the given card AID ident,
/// meaning `mx_respond_sign_card_cached` can proceed without a PIN dialog.
///
/// `card_ident` is one of the strings from `KeyInfo.cardIdents`.
Future<bool> hasCachedCardPin({required String cardIdent}) =>
    RustLib.instance.api.crateApiSimpleHasCachedCardPin(cardIdent: cardIdent);

/// Approve an `ssh.sign_request` for a card-backed key using a cached PIN.
///
/// Returns an error if no PIN is cached for any card associated with this key.
/// This is the auto-approve path after the first successful `mx_respond_sign_card`.
///
/// Not available on Android / iOS (no PC/SC subsystem).
Future<void> mxRespondSignCardCached({
  required String roomId,
  required String requestId,
}) => RustLib.instance.api.crateApiSimpleMxRespondSignCardCached(
  roomId: roomId,
  requestId: requestId,
);

/// Return the number of User PIN attempts remaining for a connected YubiKey /
/// OpenPGP card.  No PIN is required — this only reads PW status bytes.
///
/// `card_ident` is one of the strings from `KeyInfo.cardIdents`
/// (e.g. `"0006:17684870"`).  Returns an error if no card with that ident is
/// currently connected or accessible.
///
/// Not available on Android / iOS (no PC/SC subsystem).
Future<int> getCardPinRetries({required String cardIdent}) =>
    RustLib.instance.api.crateApiSimpleGetCardPinRetries(cardIdent: cardIdent);

/// Approve an `ssh.sign_request` without a passphrase dialog.
///
/// Fast path: if a decrypted keypair is cached (key-cache enabled and at least
/// one prior `mx_respond_sign` succeeded), signs in microseconds.
///
/// Slow fallback: if only the passphrase is cached, re-runs the KDF (~9 s on
/// a Mac; same cost as a fresh `mx_respond_sign`).
///
/// Returns an error if neither cache has an entry for this key.
///
/// This is also the entry point for biometric-gated approval: once the
/// platform biometric check succeeds, call this directly.
Future<void> mxRespondSignCached({
  required String roomId,
  required String requestId,
}) => RustLib.instance.api.crateApiSimpleMxRespondSignCached(
  roomId: roomId,
  requestId: requestId,
);

/// Reject an `ssh.sign_request`: send an error response and discard the request.
Future<void> mxRejectSign({
  required String roomId,
  required String requestId,
}) => RustLib.instance.api.crateApiSimpleMxRejectSign(
  roomId: roomId,
  requestId: requestId,
);

Future<List<MxDeviceInfo>> mxListDevices() =>
    RustLib.instance.api.crateApiSimpleMxListDevices();

/// Start a SAS device verification flow.  Events are pushed to `sink`:
///   1. `Waiting`          — waiting for a request from another session
///   2. `RequestReceived`  — request accepted, SAS key exchange in progress
///   3. `Emojis { … }`    — show these seven emojis to the user
///   4. `Done`             — emojis matched, device now verified
///   5. `Cancelled { … }` — flow failed or user said no match
///
/// After receiving `Emojis`, call `mx_confirm_verify(true/false)` to proceed.
Stream<MxVerifyEvent> mxStartVerify() =>
    RustLib.instance.api.crateApiSimpleMxStartVerify();

/// Respond to an active verification after seeing the emojis.
/// `confirmed = true` means the emojis match; `false` means mismatch.
Future<void> mxConfirmVerify({required bool confirmed}) =>
    RustLib.instance.api.crateApiSimpleMxConfirmVerify(confirmed: confirmed);

/// List all locally-owned device keys under `<store>/bus/devices/`.
Future<List<BusOwnDevice>> busListOwnDevices() =>
    RustLib.instance.api.crateApiSimpleBusListOwnDevices();

/// List all peer certs registered under `<store>/bus/peers/`.
Future<List<BusPeer>> busListPeers() =>
    RustLib.instance.api.crateApiSimpleBusListPeers();

/// Remove a peer cert by device_id from `<store>/bus/peers/`.
/// Returns `true` if the cert was found and deleted, `false` if it did not exist.
Future<bool> busRemovePeer({required String deviceId}) =>
    RustLib.instance.api.crateApiSimpleBusRemovePeer(deviceId: deviceId);

/// Start the in-process SSH agent.
///
/// - `label`: device label used as the bus identity (defaults to the system
///   hostname, same as `p43 ssh-agent --device <label>`).
/// - `socket_path`: Unix socket path (defaults to `p43-ssh-agent.sock` next to
///   the key store).
///
/// Returns the resolved socket path on success.  The agent registers with the
/// bus authority on first run and thereafter reuses the stored cert.
///
/// Desktop-only (macOS / Linux).  Returns an error on iOS / Android.
Future<String> sshAgentStart({String? label, String? socketPath}) => RustLib
    .instance
    .api
    .crateApiSimpleSshAgentStart(label: label, socketPath: socketPath);

/// Stop the in-process SSH agent.
///
/// Sends a stop signal to the running agent task; the Unix socket is unlinked
/// before the task exits.  Returns an error when no agent is running.
Future<void> sshAgentStop() =>
    RustLib.instance.api.crateApiSimpleSshAgentStop();

/// Returns `true` if the in-process SSH agent is currently running.
Future<bool> sshAgentIsRunning() =>
    RustLib.instance.api.crateApiSimpleSshAgentIsRunning();

/// Returns the Unix socket path of the running in-process SSH agent, or `None`
/// when no agent is running.
Future<String?> sshAgentSocketPath() =>
    RustLib.instance.api.crateApiSimpleSshAgentSocketPath();

/// List all gate-key ids present on disk.
Future<List<String>> gateKeyList() =>
    RustLib.instance.api.crateApiSimpleGateKeyList();

/// Create a new gate-key sealed with [passphrase].
///
/// Returns both the [key_id] (for future revocation) and the [master_hex]
/// so the caller can optionally store it in the OS secure enclave for
/// biometric unlock.  The passphrase-sealed file is always written.
Future<GateKeyCreated> gateKeyCreate({required String passphrase}) =>
    RustLib.instance.api.crateApiSimpleGateKeyCreate(passphrase: passphrase);

/// Add an additional passphrase lock for an existing master secret.
///
/// Call this when the user already unlocked the wallet (via any method)
/// and wants to add a new passphrase — e.g. adding a backup pin after
/// biometric setup.
Future<String> gateKeySealPassphrase({
  required String masterHex,
  required String passphrase,
}) => RustLib.instance.api.crateApiSimpleGateKeySealPassphrase(
  masterHex: masterHex,
  passphrase: passphrase,
);

/// Verify [passphrase] and return the level1_key as a hex string.
///
/// The biometric path stores this hex string in the OS secure enclave so
/// Touch ID can unlock the wallet without re-prompting the passphrase.
Future<String> gateKeyVerify({required String passphrase}) =>
    RustLib.instance.api.crateApiSimpleGateKeyVerify(passphrase: passphrase);

/// Change the passphrase for the gate-key that [old_passphrase] unlocks.
/// Returns the key_id.
Future<String> gateKeyChangePassphrase({
  required String oldPassphrase,
  required String newPassphrase,
}) => RustLib.instance.api.crateApiSimpleGateKeyChangePassphrase(
  oldPassphrase: oldPassphrase,
  newPassphrase: newPassphrase,
);

/// Revoke (delete) a gate-key by [key_id].
Future<void> gateKeyRevoke({required String keyId}) =>
    RustLib.instance.api.crateApiSimpleGateKeyRevoke(keyId: keyId);

/// Returns true if at least one gate-key is configured.
Future<bool> gateKeyIsConfigured() =>
    RustLib.instance.api.crateApiSimpleGateKeyIsConfigured();

/// List all wallet credentials.  Requires the master secret (from gate-key unlock).
Future<List<WalletEntry>> walletListWithIds({required String masterHex}) =>
    RustLib.instance.api.crateApiSimpleWalletListWithIds(masterHex: masterHex);

/// Add a YubiKey reference to the wallet.
///
/// Reads the card fingerprint from the connected card, stores
/// {label, pin} in the wallet encrypted with [master_hex].
/// If [card_ident] is None, uses the first connected card.
Future<void> walletAddYubikeyRef({
  required String masterHex,
  required String label,
  required String pin,
  String? cardIdent,
}) => RustLib.instance.api.crateApiSimpleWalletAddYubikeyRef(
  masterHex: masterHex,
  label: label,
  pin: pin,
  cardIdent: cardIdent,
);

/// Add an SSH private key to the wallet.
///
/// [private_key_bytes] is the raw OpenSSH private key file content.
/// If the key is passphrase-protected, provide [ssh_passphrase].
/// The key is decrypted before storage — the wallet AES-GCM is the outer protection.
Future<String> walletAddSshKey({
  required String masterHex,
  required List<int> privateKeyBytes,
  String? sshPassphrase,
  String? comment,
}) => RustLib.instance.api.crateApiSimpleWalletAddSshKey(
  masterHex: masterHex,
  privateKeyBytes: privateKeyBytes,
  sshPassphrase: sshPassphrase,
  comment: comment,
);

/// Read the full detail for a single wallet entry identified by its chain name.
Future<WalletCredentialDetail> walletGetCredential({
  required String masterHex,
  required String chainName,
}) => RustLib.instance.api.crateApiSimpleWalletGetCredential(
  masterHex: masterHex,
  chainName: chainName,
);

/// Tombstone a wallet entry by chain name (irreversible on the append-only store).
/// Import an armored OpenPGP secret key into the wallet.
///
/// The key is stored **unencrypted** — the gate-key AES-GCM is the outer
/// protection.  If the key on disk is passphrase-protected, supply
/// `passphrase` to decrypt it before storage (so no passphrase is ever needed
/// at use time).
Future<void> walletAddPgpKey({
  required String masterHex,
  required String keyArmored,
  String? passphrase,
  String? label,
}) => RustLib.instance.api.crateApiSimpleWalletAddPgpKey(
  masterHex: masterHex,
  keyArmored: keyArmored,
  passphrase: passphrase,
  label: label,
);

/// Load PGP key metadata from a wallet `pgp-key` chain for the detail sheet.
Future<WalletPgpKeyInfo> walletGetPgpKeyInfo({
  required String masterHex,
  required String chainName,
}) => RustLib.instance.api.crateApiSimpleWalletGetPgpKeyInfo(
  masterHex: masterHex,
  chainName: chainName,
);

/// Read all three card slots for a `yubikey-ref` wallet entry and return them
/// in the same [`WalletPgpKeyInfo`] shape used by PGP keys.
///
/// Each slot becomes a [`SubkeyInfo`] with its SSH public key (where the card
/// algorithm has an SSH equivalent).  The card must be connected; slots that
/// cannot be read are silently omitted rather than failing the whole call.
Future<WalletPgpKeyInfo> walletGetYubikeyInfo({
  required String masterHex,
  required String chainName,
}) => RustLib.instance.api.crateApiSimpleWalletGetYubikeyInfo(
  masterHex: masterHex,
  chainName: chainName,
);

/// Tombstone a wallet entry by chain name (irreversible on the append-only store).
Future<void> walletRemoveEntry({
  required String masterHex,
  required String chainName,
}) => RustLib.instance.api.crateApiSimpleWalletRemoveEntry(
  masterHex: masterHex,
  chainName: chainName,
);

@freezed
sealed class AgentRequest with _$AgentRequest {
  const AgentRequest._();

  /// The desktop wants the list of available SSH public keys.
  const factory AgentRequest.listKeys({required String requestId}) =
      AgentRequest_ListKeys;

  /// The desktop wants to sign `data` (base64) with the key at `fingerprint`.
  const factory AgentRequest.sign({
    required String requestId,
    required String fingerprint,
    required String description,

    /// Label from the sender's bus certificate (empty if unauthenticated).
    required String deviceLabel,

    /// Stable device identifier from the sender's bus certificate (empty if unauthenticated).
    required String deviceId,
  }) = AgentRequest_Sign;
}

@freezed
sealed class AppMessage with _$AppMessage {
  const AppMessage._();

  /// An SSH-agent protocol event (list-keys or sign request).
  const factory AppMessage.agentEvent({required AgentRequest event}) =
      AppMessage_AgentEvent;

  /// A bus device-registration CSR event.
  const factory AppMessage.busEvent({required BusCsrEvent event}) =
      AppMessage_BusEvent;

  /// A `BusSecure` message arrived but the authority session is locked.
  /// The UI should navigate to Devices → Authority so the user can unlock.
  const factory AppMessage.sessionLockRequired() =
      AppMessage_SessionLockRequired;
}

/// Exported authority key bundle — encrypted private scalar + public key.
///
/// Both fields are required to fully restore the authority on another device.
class AuthorityKeyExport {
  /// Raw bytes of `authority.key.enc` (OpenPGP-encrypted CBOR blob).
  final Uint8List keyEnc;

  /// Raw bytes of `authority.pub.cbor` (CBOR-encoded [`AuthorityPub`]).
  final Uint8List pubCbor;

  const AuthorityKeyExport({required this.keyEnc, required this.pubCbor});

  @override
  int get hashCode => keyEnc.hashCode ^ pubCbor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AuthorityKeyExport &&
          runtimeType == other.runtimeType &&
          keyEnc == other.keyEnc &&
          pubCbor == other.pubCbor;
}

/// A pending device registration request surfaced from the Matrix room.
class BusCsrEvent {
  final String requestId;
  final String deviceLabel;
  final String deviceId;

  /// Base64-encoded COSE_Sign1 CSR bytes — passed back to mx_respond_csr.
  final String csrB64;

  const BusCsrEvent({
    required this.requestId,
    required this.deviceLabel,
    required this.deviceId,
    required this.csrB64,
  });

  @override
  int get hashCode =>
      requestId.hashCode ^
      deviceLabel.hashCode ^
      deviceId.hashCode ^
      csrB64.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BusCsrEvent &&
          runtimeType == other.runtimeType &&
          requestId == other.requestId &&
          deviceLabel == other.deviceLabel &&
          deviceId == other.deviceId &&
          csrB64 == other.csrB64;
}

/// Summary of a locally-owned device key (own side).
class BusOwnDevice {
  final String label;
  final String deviceId;
  final bool hasCert;
  final bool hasCsr;

  /// Unix timestamp of cert expiry, or `None` if absent / never expires.
  final PlatformInt64? certExp;

  const BusOwnDevice({
    required this.label,
    required this.deviceId,
    required this.hasCert,
    required this.hasCsr,
    this.certExp,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      deviceId.hashCode ^
      hasCert.hashCode ^
      hasCsr.hashCode ^
      certExp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BusOwnDevice &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          deviceId == other.deviceId &&
          hasCert == other.hasCert &&
          hasCsr == other.hasCsr &&
          certExp == other.certExp;
}

/// Summary of a registered peer device (authority side).
class BusPeer {
  final String deviceId;
  final String label;
  final PlatformInt64 issuedAt;
  final PlatformInt64? expiresAt;

  const BusPeer({
    required this.deviceId,
    required this.label,
    required this.issuedAt,
    this.expiresAt,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      label.hashCode ^
      issuedAt.hashCode ^
      expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BusPeer &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          label == other.label &&
          issuedAt == other.issuedAt &&
          expiresAt == other.expiresAt;
}

/// Summary of a connected OpenPGP card returned by [list_connected_cards].
class ConnectedCardInfo {
  final String ident;
  final String cardholderName;
  final String? sigFingerprint;
  final String? authFingerprint;

  const ConnectedCardInfo({
    required this.ident,
    required this.cardholderName,
    this.sigFingerprint,
    this.authFingerprint,
  });

  @override
  int get hashCode =>
      ident.hashCode ^
      cardholderName.hashCode ^
      sigFingerprint.hashCode ^
      authFingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectedCardInfo &&
          runtimeType == other.runtimeType &&
          ident == other.ident &&
          cardholderName == other.cardholderName &&
          sigFingerprint == other.sigFingerprint &&
          authFingerprint == other.authFingerprint;
}

/// A gate-key created from a passphrase.
///
/// The passphrase is always required for first-time setup.
/// [master_hex] is the 32-byte level1_key as hex — store it in the OS
/// secure enclave if biometric unlock is also desired.
class GateKeyCreated {
  final String keyId;
  final String masterHex;

  const GateKeyCreated({required this.keyId, required this.masterHex});

  @override
  int get hashCode => keyId.hashCode ^ masterHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GateKeyCreated &&
          runtimeType == other.runtimeType &&
          keyId == other.keyId &&
          masterHex == other.masterHex;
}

/// A key entry returned to Dart — mirrors p43::key_store::store::KeyEntry.
class KeyInfo {
  final String fingerprint;
  final String uid;
  final String algo;
  final bool hasSecret;

  /// Whether this key is active in the SSH agent.
  final bool enabled;

  /// Application Identifier strings of YubiKeys registered against this key.
  /// Empty for pure soft keys.
  final List<String> cardIdents;

  /// All subkeys (including primary) with their roles and algorithms.
  final List<SubkeyInfo> subkeys;

  const KeyInfo({
    required this.fingerprint,
    required this.uid,
    required this.algo,
    required this.hasSecret,
    required this.enabled,
    required this.cardIdents,
    required this.subkeys,
  });

  @override
  int get hashCode =>
      fingerprint.hashCode ^
      uid.hashCode ^
      algo.hashCode ^
      hasSecret.hashCode ^
      enabled.hashCode ^
      cardIdents.hashCode ^
      subkeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyInfo &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          uid == other.uid &&
          algo == other.algo &&
          hasSecret == other.hasSecret &&
          enabled == other.enabled &&
          cardIdents == other.cardIdents &&
          subkeys == other.subkeys;
}

/// Sealing status for a single keystore key.
class KeySealStatus {
  final String fingerprint;
  final String uid;
  final bool isSealed;

  /// `true` → card key (unlock with PIN); `false` → soft key (unlock with passphrase).
  final bool hasCard;

  const KeySealStatus({
    required this.fingerprint,
    required this.uid,
    required this.isSealed,
    required this.hasCard,
  });

  @override
  int get hashCode =>
      fingerprint.hashCode ^
      uid.hashCode ^
      isSealed.hashCode ^
      hasCard.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeySealStatus &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          uid == other.uid &&
          isSealed == other.isSealed &&
          hasCard == other.hasCard;
}

class MxDeviceInfo {
  final String deviceId;
  final String displayName;
  final bool isCurrent;

  const MxDeviceInfo({
    required this.deviceId,
    required this.displayName,
    required this.isCurrent,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ displayName.hashCode ^ isCurrent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MxDeviceInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          displayName == other.displayName &&
          isCurrent == other.isCurrent;
}

class MxEmojiInfo {
  final String symbol;
  final String description;

  const MxEmojiInfo({required this.symbol, required this.description});

  @override
  int get hashCode => symbol.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MxEmojiInfo &&
          runtimeType == other.runtimeType &&
          symbol == other.symbol &&
          description == other.description;
}

class MxMessage {
  final String sender;
  final String body;

  const MxMessage({required this.sender, required this.body});

  @override
  int get hashCode => sender.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MxMessage &&
          runtimeType == other.runtimeType &&
          sender == other.sender &&
          body == other.body;
}

class MxRoomInfo {
  final String roomId;
  final String name;
  final bool isEncrypted;

  const MxRoomInfo({
    required this.roomId,
    required this.name,
    required this.isEncrypted,
  });

  @override
  int get hashCode => roomId.hashCode ^ name.hashCode ^ isEncrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MxRoomInfo &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          name == other.name &&
          isEncrypted == other.isEncrypted;
}

@freezed
sealed class MxVerifyEvent with _$MxVerifyEvent {
  const MxVerifyEvent._();

  const factory MxVerifyEvent.waiting() = MxVerifyEvent_Waiting;
  const factory MxVerifyEvent.requestReceived() = MxVerifyEvent_RequestReceived;
  const factory MxVerifyEvent.emojis({required List<MxEmojiInfo> emojis}) =
      MxVerifyEvent_Emojis;
  const factory MxVerifyEvent.done() = MxVerifyEvent_Done;
  const factory MxVerifyEvent.cancelled({required String reason}) =
      MxVerifyEvent_Cancelled;
}

/// Key identity returned by [`get_ssh_key_details`].
class SshKeyDetails {
  /// Human-readable UID, e.g. `"Alice <alice@example.com>"`.
  final String name;

  /// Algorithm string, e.g. `"ed25519"`, `"rsa4096"`.
  final String algo;

  /// AID ident strings of any OpenPGP cards (YubiKeys, etc.) associated
  /// with this key entry.  Empty for pure soft keys.
  final List<String> cardIdents;

  const SshKeyDetails({
    required this.name,
    required this.algo,
    required this.cardIdents,
  });

  @override
  int get hashCode => name.hashCode ^ algo.hashCode ^ cardIdents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshKeyDetails &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          algo == other.algo &&
          cardIdents == other.cardIdents;
}

/// One subkey inside an OpenPGP cert — role + algorithm + SSH key for display.
class SubkeyInfo {
  /// Human-readable role string: "certify", "sign", "auth", "encrypt",
  /// "certify+sign", or combinations thereof.
  final String role;

  /// Algorithm name from OpenPGP, e.g. "RSA4096", "EdDSA", "ECDH".
  final String algo;

  /// OpenSSH `authorized_keys` line for this subkey, or `None` when the
  /// algorithm has no SSH equivalent (e.g. ECDH encryption keys).
  final String? opensshKey;

  const SubkeyInfo({required this.role, required this.algo, this.opensshKey});

  @override
  int get hashCode => role.hashCode ^ algo.hashCode ^ opensshKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubkeyInfo &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          algo == other.algo &&
          opensshKey == other.opensshKey;
}

/// Detail view of a single wallet credential.
class WalletCredentialDetail {
  /// `"yubikey-ref"` or `"ssh-key"`.
  final String kind;

  /// Human-readable label / comment.
  final String label;

  /// Card AID (yubikey-ref) or `SHA256:…` fingerprint (ssh-key).
  final String displayId;

  /// Full OpenSSH `authorized_keys` line.
  final String? pubkeyText;

  /// Armored OpenPGP public key packet (derived from the SSH key bytes).
  final String? pgpArmored;

  const WalletCredentialDetail({
    required this.kind,
    required this.label,
    required this.displayId,
    this.pubkeyText,
    this.pgpArmored,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      label.hashCode ^
      displayId.hashCode ^
      pubkeyText.hashCode ^
      pgpArmored.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletCredentialDetail &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          label == other.label &&
          displayId == other.displayId &&
          pubkeyText == other.pubkeyText &&
          pgpArmored == other.pgpArmored;
}

/// A wallet credential entry for display.
class WalletEntry {
  final String chainName;
  final String kind;
  final String chainId;

  const WalletEntry({
    required this.chainName,
    required this.kind,
    required this.chainId,
  });

  @override
  int get hashCode => chainName.hashCode ^ kind.hashCode ^ chainId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletEntry &&
          runtimeType == other.runtimeType &&
          chainName == other.chainName &&
          kind == other.kind &&
          chainId == other.chainId;
}

/// Full detail for a wallet PGP key — UID, algorithm, subkeys, armored pubkey.
///
/// Reuses [`SubkeyInfo`] so the Dart detail sheet can render the same
/// subkey UI without needing new generated types.
class WalletPgpKeyInfo {
  final String uid;
  final String algo;
  final String fingerprint;
  final List<SubkeyInfo> subkeys;
  final String pubkeyArmored;

  const WalletPgpKeyInfo({
    required this.uid,
    required this.algo,
    required this.fingerprint,
    required this.subkeys,
    required this.pubkeyArmored,
  });

  @override
  int get hashCode =>
      uid.hashCode ^
      algo.hashCode ^
      fingerprint.hashCode ^
      subkeys.hashCode ^
      pubkeyArmored.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletPgpKeyInfo &&
          runtimeType == other.runtimeType &&
          uid == other.uid &&
          algo == other.algo &&
          fingerprint == other.fingerprint &&
          subkeys == other.subkeys &&
          pubkeyArmored == other.pubkeyArmored;
}
