// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `default_store_dir`, `mx_store_dir`, `mx_verify_slot`, `open_store`, `to_key_info`, `tokio_rt`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`

/// Must be called once from Dart before any key operation.
/// Pass `getApplicationSupportDirectory().path` (or equivalent).
Future<void> setStoreDir({required String dir}) =>
    RustLib.instance.api.crateApiSimpleSetStoreDir(dir: dir);

/// Returns all keys in the local store (~/.config/project-43/keys).
Future<List<KeyInfo>> listKeys() =>
    RustLib.instance.api.crateApiSimpleListKeys();

/// Generates a new soft key, saves it, and returns the updated key list.
/// `passphrase: None` skips encryption (not recommended).
Future<List<KeyInfo>> generateKey({
  required String uid,
  required String algo,
  String? passphrase,
}) => RustLib.instance.api.crateApiSimpleGenerateKey(
  uid: uid,
  algo: algo,
  passphrase: passphrase,
);

/// Password login.  Persists session under the app support directory.
Future<void> mxLogin({
  required String homeserver,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiSimpleMxLogin(
  homeserver: homeserver,
  username: username,
  password: password,
);

/// Restore a previously saved session.  Returns `true` if one was found.
/// Call at startup before showing the chat UI.
Future<bool> mxRestore() => RustLib.instance.api.crateApiSimpleMxRestore();

/// Logout and delete the local session.
Future<void> mxLogout() => RustLib.instance.api.crateApiSimpleMxLogout();

/// `true` if a Matrix session is currently active (non-blocking).
Future<bool> mxIsLoggedIn() =>
    RustLib.instance.api.crateApiSimpleMxIsLoggedIn();

Future<List<MxRoomInfo>> mxListRooms() =>
    RustLib.instance.api.crateApiSimpleMxListRooms();

Future<MxRoomInfo> mxJoinRoom({required String room}) =>
    RustLib.instance.api.crateApiSimpleMxJoinRoom(room: room);

Future<void> mxSend({required String roomId, required String text}) =>
    RustLib.instance.api.crateApiSimpleMxSend(roomId: roomId, text: text);

/// Stream all messages in `room_id` (history + live).
/// Dart receives each message as an `MxMessage` event.
Stream<MxMessage> mxListen({required String roomId}) =>
    RustLib.instance.api.crateApiSimpleMxListen(roomId: roomId);

/// Return the room ID saved as the agent room in matrix-config.json, if any.
Future<String?> mxGetAgentRoom() =>
    RustLib.instance.api.crateApiSimpleMxGetAgentRoom();

/// Persist `room_id` as the default agent room in matrix-config.json.
Future<void> mxSetAgentRoom({required String roomId}) =>
    RustLib.instance.api.crateApiSimpleMxSetAgentRoom(roomId: roomId);

/// Subscribe to p43 protocol request messages arriving in `room_id`.
///
/// Only `ssh.list_keys_request` and `ssh.sign_request` events are forwarded;
/// all other room traffic is silently ignored.
Stream<AgentRequest> mxListenAgent({required String roomId}) =>
    RustLib.instance.api.crateApiSimpleMxListenAgent(roomId: roomId);

/// Respond to an `ssh.list_keys_request` with the keys held in the local store.
///
/// The key list is currently empty — wired to the key store in a follow-up.
Future<void> mxRespondListKeys({
  required String roomId,
  required String requestId,
}) => RustLib.instance.api.crateApiSimpleMxRespondListKeys(
  roomId: roomId,
  requestId: requestId,
);

Future<List<MxDeviceInfo>> mxListDevices() =>
    RustLib.instance.api.crateApiSimpleMxListDevices();

/// Start a SAS device verification flow.  Events are pushed to `sink`:
///   1. `Waiting`          — waiting for a request from another session
///   2. `RequestReceived`  — request accepted, SAS key exchange in progress
///   3. `Emojis { … }`    — show these seven emojis to the user
///   4. `Done`             — emojis matched, device now verified
///   5. `Cancelled { … }` — flow failed or user said no match
///
/// After receiving `Emojis`, call `mx_confirm_verify(true/false)` to proceed.
Stream<MxVerifyEvent> mxStartVerify() =>
    RustLib.instance.api.crateApiSimpleMxStartVerify();

/// Respond to an active verification after seeing the emojis.
/// `confirmed = true` means the emojis match; `false` means mismatch.
Future<void> mxConfirmVerify({required bool confirmed}) =>
    RustLib.instance.api.crateApiSimpleMxConfirmVerify(confirmed: confirmed);

@freezed
sealed class AgentRequest with _$AgentRequest {
  const AgentRequest._();

  /// The desktop wants the list of available SSH public keys.
  const factory AgentRequest.listKeys({required String requestId}) =
      AgentRequest_ListKeys;

  /// The desktop wants to sign `data` (base64) with the key at `fingerprint`.
  const factory AgentRequest.sign({
    required String requestId,
    required String fingerprint,
    required String description,
  }) = AgentRequest_Sign;
}

/// A key entry returned to Dart — mirrors p43::key_store::store::KeyEntry.
class KeyInfo {
  final String fingerprint;
  final String uid;
  final String algo;
  final bool hasSecret;

  const KeyInfo({
    required this.fingerprint,
    required this.uid,
    required this.algo,
    required this.hasSecret,
  });

  @override
  int get hashCode =>
      fingerprint.hashCode ^ uid.hashCode ^ algo.hashCode ^ hasSecret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyInfo &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          uid == other.uid &&
          algo == other.algo &&
          hasSecret == other.hasSecret;
}

class MxDeviceInfo {
  final String deviceId;
  final String displayName;
  final bool isCurrent;

  const MxDeviceInfo({
    required this.deviceId,
    required this.displayName,
    required this.isCurrent,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ displayName.hashCode ^ isCurrent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MxDeviceInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          displayName == other.displayName &&
          isCurrent == other.isCurrent;
}

class MxEmojiInfo {
  final String symbol;
  final String description;

  const MxEmojiInfo({required this.symbol, required this.description});

  @override
  int get hashCode => symbol.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MxEmojiInfo &&
          runtimeType == other.runtimeType &&
          symbol == other.symbol &&
          description == other.description;
}

class MxMessage {
  final String sender;
  final String body;

  const MxMessage({required this.sender, required this.body});

  @override
  int get hashCode => sender.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MxMessage &&
          runtimeType == other.runtimeType &&
          sender == other.sender &&
          body == other.body;
}

class MxRoomInfo {
  final String roomId;
  final String name;
  final bool isEncrypted;

  const MxRoomInfo({
    required this.roomId,
    required this.name,
    required this.isEncrypted,
  });

  @override
  int get hashCode => roomId.hashCode ^ name.hashCode ^ isEncrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MxRoomInfo &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          name == other.name &&
          isEncrypted == other.isEncrypted;
}

@freezed
sealed class MxVerifyEvent with _$MxVerifyEvent {
  const MxVerifyEvent._();

  const factory MxVerifyEvent.waiting() = MxVerifyEvent_Waiting;
  const factory MxVerifyEvent.requestReceived() = MxVerifyEvent_RequestReceived;
  const factory MxVerifyEvent.emojis({required List<MxEmojiInfo> emojis}) =
      MxVerifyEvent_Emojis;
  const factory MxVerifyEvent.done() = MxVerifyEvent_Done;
  const factory MxVerifyEvent.cancelled({required String reason}) =
      MxVerifyEvent_Cancelled;
}
