// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `card_pin_cache`, `default_store_dir`, `mx_store_dir`, `mx_verify_slot`, `open_store`, `passphrase_cache`, `pending_signs`, `signing_key_cache`, `subkeys_for`, `to_key_info`, `tokio_rt`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PendingSign`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`

/// Initialise tracing.
///
/// Pass an empty string for **local mode** (fmt output, zero network overhead).
/// Pass `"https://otel.adviser.com"` to export spans to the OTel Collector.
///
/// If the endpoint is unreachable the SDK retries silently and drops spans
/// after the retry budget — the app is never blocked.
///
/// Compiled as a no-op when the `p43` library is built without
/// `--features telemetry`.
Future<void> initTelemetry({required String endpoint}) =>
    RustLib.instance.api.crateApiSimpleInitTelemetry(endpoint: endpoint);

/// Shut down the OTel provider and flush all pending spans.
/// Call before the app exits.
Future<void> shutdownTelemetry() =>
    RustLib.instance.api.crateApiSimpleShutdownTelemetry();

/// Inject a W3C `traceparent` header for the current thread.
///
/// Dart should call this **immediately before** any FRB function that creates
/// a tracing span, then call [clearActiveTraceparent] once the call returns.
/// This stitches the Flutter span tree and the Rust span tree into a single
/// distributed trace in Jaeger.
///
/// The value must follow the W3C Trace Context format:
/// `00-<trace-id-32hex>-<parent-id-16hex>-<flags-2hex>`
Future<void> setActiveTraceparent({required String traceparent}) => RustLib
    .instance
    .api
    .crateApiSimpleSetActiveTraceparent(traceparent: traceparent);

/// Clear the stored traceparent for the current thread.
/// Call after every FRB call that was preceded by [setActiveTraceparent].
Future<void> clearActiveTraceparent() =>
    RustLib.instance.api.crateApiSimpleClearActiveTraceparent();

/// Must be called once from Dart before any key operation.
/// Pass `getApplicationSupportDirectory().path` (or equivalent).
Future<void> setStoreDir({required String dir}) =>
    RustLib.instance.api.crateApiSimpleSetStoreDir(dir: dir);

/// Returns all keys in the local store (~/.config/project-43/keys).
Future<List<KeyInfo>> listKeys() =>
    RustLib.instance.api.crateApiSimpleListKeys();

/// Verify that `passphrase` correctly decrypts the secret key at `fingerprint`.
///
/// Returns `Ok(())` on success, or an error whose message can be shown to
/// the user (e.g. "Failed to decrypt secret keys — wrong passphrase?").
Future<void> verifyKeyPassphrase({
  required String fingerprint,
  required String passphrase,
}) => RustLib.instance.api.crateApiSimpleVerifyKeyPassphrase(
  fingerprint: fingerprint,
  passphrase: passphrase,
);

/// Delete a key (public + secret files + index entry) from the local store.
Future<void> deleteKey({required String fingerprint}) =>
    RustLib.instance.api.crateApiSimpleDeleteKey(fingerprint: fingerprint);

/// Enable or disable a key in the SSH agent.
///
/// Disabled keys are not advertised by `ssh-add -l` and cannot be used
/// for signing.  The key files are not modified.
Future<void> setKeyEnabled({
  required String fingerprint,
  required bool enabled,
}) => RustLib.instance.api.crateApiSimpleSetKeyEnabled(
  fingerprint: fingerprint,
  enabled: enabled,
);

/// Returns the armored OpenPGP public key for the given fingerprint.
Future<String> getPublicKeyArmored({required String fingerprint}) => RustLib
    .instance
    .api
    .crateApiSimpleGetPublicKeyArmored(fingerprint: fingerprint);

/// Returns the OpenSSH `authorized_keys` line for the given fingerprint.
///
/// Uses the authentication subkey (falling back to the signing subkey).
Future<String> getPublicKeyOpenssh({required String fingerprint}) => RustLib
    .instance
    .api
    .crateApiSimpleGetPublicKeyOpenssh(fingerprint: fingerprint);

/// Resolve an SSH SHA-256 fingerprint (e.g. `SHA256:AbCd…`) to the key's
/// human-readable UID, algorithm, and associated card ident(s).
///
/// Returns `None` if no matching key is found.  Used by sign-request tiles and
/// the passphrase dialog to display key identity alongside the fingerprint.
Future<SshKeyDetails?> getSshKeyDetails({required String fingerprint}) =>
    RustLib.instance.api.crateApiSimpleGetSshKeyDetails(
      fingerprint: fingerprint,
    );

/// Generates a new soft key, saves it, and returns the updated key list.
/// `passphrase: None` skips encryption (not recommended).
Future<List<KeyInfo>> generateKey({
  required String uid,
  required String algo,
  String? passphrase,
}) => RustLib.instance.api.crateApiSimpleGenerateKey(
  uid: uid,
  algo: algo,
  passphrase: passphrase,
);

/// Return a summary of every connected OpenPGP card (no PIN required).
///
/// On macOS the system PC/SC daemon handles the transport; no additional
/// setup is needed.  Returns an empty list when no cards are present.
Future<List<ConnectedCardInfo>> listConnectedCards() =>
    RustLib.instance.api.crateApiSimpleListConnectedCards();

/// Import a key from a connected OpenPGP card into the local key store.
///
/// Reads the signing-slot public key, uses the card to self-certify the UID
/// binding, saves `<fingerprint>.pub.asc` and `<fingerprint>.card.json`, and
/// returns the updated key list.
///
/// - `card_ident`: AID ident string from [list_connected_cards].
/// - `uid`: user ID string for the cert (e.g. `"Alice <alice@example.com>"`).
///   Pass the empty string to fall back to the cardholder name on the card.
/// - `pin`: card User Signing PIN (unlocks the SIG slot).
Future<List<KeyInfo>> importCard({
  required String cardIdent,
  required String uid,
  required String pin,
}) => RustLib.instance.api.crateApiSimpleImportCard(
  cardIdent: cardIdent,
  uid: uid,
  pin: pin,
);

/// Import an OpenSSH private key file into the local key store as an OpenPGP
/// cert.
///
/// - `pem_bytes`: raw contents of the `id_ed25519` / `id_rsa` file.
/// - `uid_override`: UID string (e.g. `"Alice <alice@example.com>"`).  Pass the
///   empty string to derive from the SSH key's comment field.
/// - `ssh_passphrase`: passphrase that protects the SSH file itself (if any).
/// - `openpgp_passphrase`: passphrase to encrypt the stored OpenPGP secret key.
///   Pass `None` to store the key unencrypted (only do this on a secure device).
///
/// Returns the hex fingerprint of the newly imported cert and the updated key
/// list.
Future<List<KeyInfo>> importSshKey({
  required List<int> pemBytes,
  required String uidOverride,
  String? sshPassphrase,
  String? openpgpPassphrase,
}) => RustLib.instance.api.crateApiSimpleImportSshKey(
  pemBytes: pemBytes,
  uidOverride: uidOverride,
  sshPassphrase: sshPassphrase,
  openpgpPassphrase: openpgpPassphrase,
);

/// Import an armored OpenPGP private key (TSK) into the local key store.
///
/// `armored` is the full text of a `-----BEGIN PGP PRIVATE KEY BLOCK-----`
/// message.  The passphrase (if any) is not required at import time.
///
/// Returns the updated key list.
Future<List<KeyInfo>> importOpenpgpKey({required String armored}) =>
    RustLib.instance.api.crateApiSimpleImportOpenpgpKey(armored: armored);

/// Register a YubiKey (or other OpenPGP card) AID with a key entry.
///
/// Creates or updates `<fingerprint>.card.json` in the key store.  The same
/// key can be associated with multiple card AIDs — useful when a user has two
/// identical-content YubiKeys.
///
/// `card_ident` should be the AID string shown by `p43 key list --verbose`
/// or returned by `tx.application_identifier()?.ident()` in the card layer.
Future<void> registerCardIdent({
  required String fingerprint,
  required String cardIdent,
}) => RustLib.instance.api.crateApiSimpleRegisterCardIdent(
  fingerprint: fingerprint,
  cardIdent: cardIdent,
);

/// Password login.  Persists session under the app support directory.
Future<void> mxLogin({
  required String homeserver,
  required String username,
  required String password,
}) => RustLib.instance.api.crateApiSimpleMxLogin(
  homeserver: homeserver,
  username: username,
  password: password,
);

/// Restore a previously saved session.  Returns `true` if one was found.
/// Call at startup before showing the chat UI.
Future<bool> mxRestore() => RustLib.instance.api.crateApiSimpleMxRestore();

/// Logout and delete the local session.
Future<void> mxLogout() => RustLib.instance.api.crateApiSimpleMxLogout();

/// `true` if a Matrix session is currently active (non-blocking).
Future<bool> mxIsLoggedIn() =>
    RustLib.instance.api.crateApiSimpleMxIsLoggedIn();

Future<List<MxRoomInfo>> mxListRooms() =>
    RustLib.instance.api.crateApiSimpleMxListRooms();

Future<MxRoomInfo> mxJoinRoom({required String room}) =>
    RustLib.instance.api.crateApiSimpleMxJoinRoom(room: room);

Future<void> mxSend({required String roomId, required String text}) =>
    RustLib.instance.api.crateApiSimpleMxSend(roomId: roomId, text: text);

/// Stream all messages in `room_id` (history + live).
/// Dart receives each message as an `MxMessage` event.
Stream<MxMessage> mxListen({required String roomId}) =>
    RustLib.instance.api.crateApiSimpleMxListen(roomId: roomId);

/// Return the room ID saved as the agent room in matrix-config.json, if any.
Future<String?> mxGetAgentRoom() =>
    RustLib.instance.api.crateApiSimpleMxGetAgentRoom();

/// Persist `room_id` as the default agent room in matrix-config.json.
Future<void> mxSetAgentRoom({required String roomId}) =>
    RustLib.instance.api.crateApiSimpleMxSetAgentRoom(roomId: roomId);

/// Subscribe to p43 protocol request messages arriving in `room_id`.
///
/// Only `ssh.list_keys_request` and `ssh.sign_request` events are forwarded;
/// all other room traffic is silently ignored.
///
/// On startup the last persisted `agent_since` token (if any) is loaded from
/// `matrix-config.json` and passed to the sync so old messages are not replayed.
/// The token is saved on **every** sync batch so it survives process kills and
/// crashes — no history replay on reconnect regardless of how the app exited.
Stream<AgentRequest> mxListenAgent({required String roomId}) =>
    RustLib.instance.api.crateApiSimpleMxListenAgent(roomId: roomId);

/// Respond to an `ssh.list_keys_request` with the keys held in the local store.
Future<void> mxRespondListKeys({
  required String roomId,
  required String requestId,
}) => RustLib.instance.api.crateApiSimpleMxRespondListKeys(
  roomId: roomId,
  requestId: requestId,
);

/// Returns `true` if cached credentials exist for the given SSH fingerprint,
/// meaning `mx_respond_sign_cached` can proceed without a passphrase dialog.
///
/// Returns `true` when either:
/// - A decrypted keypair is cached (key-cache enabled) → fast, microseconds.
/// - A passphrase is cached (key-cache disabled) → slow, re-runs KDF (~9 s).
///
/// Dart uses this to decide whether to auto-approve or show the dialog.
/// When biometric approval is added, this is also the gate for whether
/// biometric confirmation suffices or the user must type their passphrase.
Future<bool> hasCachedPassphrase({required String fingerprint}) => RustLib
    .instance
    .api
    .crateApiSimpleHasCachedPassphrase(fingerprint: fingerprint);

/// Enable or disable the in-memory signing-key cache.
///
/// When `enabled`:
/// - `mx_respond_sign` extracts and caches the decrypted Ed25519 keypair bytes
///   so subsequent `mx_respond_sign_cached` calls skip the KDF entirely.
///
/// When `disabled`:
/// - The signing-key cache is cleared immediately.
/// - `mx_respond_sign_cached` falls back to the passphrase cache + KDF.
///
/// Call at startup with the persisted setting value, and again whenever the
/// user toggles the setting.
Future<void> mxSetCacheKeyEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiSimpleMxSetCacheKeyEnabled(enabled: enabled);

/// Clear all in-memory credential caches (passphrase + signing key).
///
/// Does **not** affect the `KEY_CACHE_ENABLED` flag — the next successful
/// `mx_respond_sign` will repopulate the caches if caching is still enabled.
///
/// Call when the configured session timeout expires or the screen locks.
Future<void> mxClearCaches() =>
    RustLib.instance.api.crateApiSimpleMxClearCaches();

/// Approve an `ssh.sign_request` using an explicitly supplied passphrase.
///
/// On success:
/// - The passphrase is stored in the in-memory cache (slow fallback path).
/// - If "cache decrypted key" is enabled, the decrypted Ed25519 keypair bytes
///   are also cached so subsequent auto-approve signs skip the KDF entirely.
Future<void> mxRespondSign({
  required String roomId,
  required String requestId,
  required String passphrase,
}) => RustLib.instance.api.crateApiSimpleMxRespondSign(
  roomId: roomId,
  requestId: requestId,
  passphrase: passphrase,
);

/// Approve an `ssh.sign_request` for a card-backed key using the card's User PIN.
///
/// The card's AUTH slot is used for signing (same slot the SSH agent uses).
/// The User PIN (typically 6+ digits on YubiKey) unlocks the AUTH slot — it
/// is NOT the Admin PIN or the Signing PIN.
///
/// On success the PIN is cached in memory keyed by card AID ident so that
/// `mx_respond_sign_card_cached` can skip the PIN dialog for subsequent requests.
Future<void> mxRespondSignCard({
  required String roomId,
  required String requestId,
  required String pin,
}) => RustLib.instance.api.crateApiSimpleMxRespondSignCard(
  roomId: roomId,
  requestId: requestId,
  pin: pin,
);

/// Returns `true` if a cached PIN exists for the given card AID ident,
/// meaning `mx_respond_sign_card_cached` can proceed without a PIN dialog.
///
/// `card_ident` is one of the strings from `KeyInfo.cardIdents`.
Future<bool> hasCachedCardPin({required String cardIdent}) =>
    RustLib.instance.api.crateApiSimpleHasCachedCardPin(cardIdent: cardIdent);

/// Approve an `ssh.sign_request` for a card-backed key using a cached PIN.
///
/// Returns an error if no PIN is cached for any card associated with this key.
/// This is the auto-approve path after the first successful `mx_respond_sign_card`.
Future<void> mxRespondSignCardCached({
  required String roomId,
  required String requestId,
}) => RustLib.instance.api.crateApiSimpleMxRespondSignCardCached(
  roomId: roomId,
  requestId: requestId,
);

/// Return the number of User PIN attempts remaining for a connected YubiKey /
/// OpenPGP card.  No PIN is required — this only reads PW status bytes.
///
/// `card_ident` is one of the strings from `KeyInfo.cardIdents`
/// (e.g. `"0006:17684870"`).  Returns an error if no card with that ident is
/// currently connected or accessible.
Future<int> getCardPinRetries({required String cardIdent}) =>
    RustLib.instance.api.crateApiSimpleGetCardPinRetries(cardIdent: cardIdent);

/// Approve an `ssh.sign_request` without a passphrase dialog.
///
/// Fast path: if a decrypted keypair is cached (key-cache enabled and at least
/// one prior `mx_respond_sign` succeeded), signs in microseconds.
///
/// Slow fallback: if only the passphrase is cached, re-runs the KDF (~9 s on
/// a Mac; same cost as a fresh `mx_respond_sign`).
///
/// Returns an error if neither cache has an entry for this key.
///
/// This is also the entry point for biometric-gated approval: once the
/// platform biometric check succeeds, call this directly.
Future<void> mxRespondSignCached({
  required String roomId,
  required String requestId,
}) => RustLib.instance.api.crateApiSimpleMxRespondSignCached(
  roomId: roomId,
  requestId: requestId,
);

/// Reject an `ssh.sign_request`: send an error response and discard the request.
Future<void> mxRejectSign({
  required String roomId,
  required String requestId,
}) => RustLib.instance.api.crateApiSimpleMxRejectSign(
  roomId: roomId,
  requestId: requestId,
);

Future<List<MxDeviceInfo>> mxListDevices() =>
    RustLib.instance.api.crateApiSimpleMxListDevices();

/// Start a SAS device verification flow.  Events are pushed to `sink`:
///   1. `Waiting`          — waiting for a request from another session
///   2. `RequestReceived`  — request accepted, SAS key exchange in progress
///   3. `Emojis { … }`    — show these seven emojis to the user
///   4. `Done`             — emojis matched, device now verified
///   5. `Cancelled { … }` — flow failed or user said no match
///
/// After receiving `Emojis`, call `mx_confirm_verify(true/false)` to proceed.
Stream<MxVerifyEvent> mxStartVerify() =>
    RustLib.instance.api.crateApiSimpleMxStartVerify();

/// Respond to an active verification after seeing the emojis.
/// `confirmed = true` means the emojis match; `false` means mismatch.
Future<void> mxConfirmVerify({required bool confirmed}) =>
    RustLib.instance.api.crateApiSimpleMxConfirmVerify(confirmed: confirmed);

@freezed
sealed class AgentRequest with _$AgentRequest {
  const AgentRequest._();

  /// The desktop wants the list of available SSH public keys.
  const factory AgentRequest.listKeys({required String requestId}) =
      AgentRequest_ListKeys;

  /// The desktop wants to sign `data` (base64) with the key at `fingerprint`.
  const factory AgentRequest.sign({
    required String requestId,
    required String fingerprint,
    required String description,
  }) = AgentRequest_Sign;
}

/// Summary of a connected OpenPGP card returned by [list_connected_cards].
class ConnectedCardInfo {
  final String ident;
  final String cardholderName;
  final String? sigFingerprint;
  final String? authFingerprint;

  const ConnectedCardInfo({
    required this.ident,
    required this.cardholderName,
    this.sigFingerprint,
    this.authFingerprint,
  });

  @override
  int get hashCode =>
      ident.hashCode ^
      cardholderName.hashCode ^
      sigFingerprint.hashCode ^
      authFingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectedCardInfo &&
          runtimeType == other.runtimeType &&
          ident == other.ident &&
          cardholderName == other.cardholderName &&
          sigFingerprint == other.sigFingerprint &&
          authFingerprint == other.authFingerprint;
}

/// A key entry returned to Dart — mirrors p43::key_store::store::KeyEntry.
class KeyInfo {
  final String fingerprint;
  final String uid;
  final String algo;
  final bool hasSecret;

  /// Whether this key is active in the SSH agent.
  final bool enabled;

  /// Application Identifier strings of YubiKeys registered against this key.
  /// Empty for pure soft keys.
  final List<String> cardIdents;

  /// All subkeys (including primary) with their roles and algorithms.
  final List<SubkeyInfo> subkeys;

  const KeyInfo({
    required this.fingerprint,
    required this.uid,
    required this.algo,
    required this.hasSecret,
    required this.enabled,
    required this.cardIdents,
    required this.subkeys,
  });

  @override
  int get hashCode =>
      fingerprint.hashCode ^
      uid.hashCode ^
      algo.hashCode ^
      hasSecret.hashCode ^
      enabled.hashCode ^
      cardIdents.hashCode ^
      subkeys.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyInfo &&
          runtimeType == other.runtimeType &&
          fingerprint == other.fingerprint &&
          uid == other.uid &&
          algo == other.algo &&
          hasSecret == other.hasSecret &&
          enabled == other.enabled &&
          cardIdents == other.cardIdents &&
          subkeys == other.subkeys;
}

class MxDeviceInfo {
  final String deviceId;
  final String displayName;
  final bool isCurrent;

  const MxDeviceInfo({
    required this.deviceId,
    required this.displayName,
    required this.isCurrent,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^ displayName.hashCode ^ isCurrent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MxDeviceInfo &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          displayName == other.displayName &&
          isCurrent == other.isCurrent;
}

class MxEmojiInfo {
  final String symbol;
  final String description;

  const MxEmojiInfo({required this.symbol, required this.description});

  @override
  int get hashCode => symbol.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MxEmojiInfo &&
          runtimeType == other.runtimeType &&
          symbol == other.symbol &&
          description == other.description;
}

class MxMessage {
  final String sender;
  final String body;

  const MxMessage({required this.sender, required this.body});

  @override
  int get hashCode => sender.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MxMessage &&
          runtimeType == other.runtimeType &&
          sender == other.sender &&
          body == other.body;
}

class MxRoomInfo {
  final String roomId;
  final String name;
  final bool isEncrypted;

  const MxRoomInfo({
    required this.roomId,
    required this.name,
    required this.isEncrypted,
  });

  @override
  int get hashCode => roomId.hashCode ^ name.hashCode ^ isEncrypted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MxRoomInfo &&
          runtimeType == other.runtimeType &&
          roomId == other.roomId &&
          name == other.name &&
          isEncrypted == other.isEncrypted;
}

@freezed
sealed class MxVerifyEvent with _$MxVerifyEvent {
  const MxVerifyEvent._();

  const factory MxVerifyEvent.waiting() = MxVerifyEvent_Waiting;
  const factory MxVerifyEvent.requestReceived() = MxVerifyEvent_RequestReceived;
  const factory MxVerifyEvent.emojis({required List<MxEmojiInfo> emojis}) =
      MxVerifyEvent_Emojis;
  const factory MxVerifyEvent.done() = MxVerifyEvent_Done;
  const factory MxVerifyEvent.cancelled({required String reason}) =
      MxVerifyEvent_Cancelled;
}

/// Key identity returned by [`get_ssh_key_details`].
class SshKeyDetails {
  /// Human-readable UID, e.g. `"Alice <alice@example.com>"`.
  final String name;

  /// Algorithm string, e.g. `"ed25519"`, `"rsa4096"`.
  final String algo;

  /// AID ident strings of any OpenPGP cards (YubiKeys, etc.) associated
  /// with this key entry.  Empty for pure soft keys.
  final List<String> cardIdents;

  const SshKeyDetails({
    required this.name,
    required this.algo,
    required this.cardIdents,
  });

  @override
  int get hashCode => name.hashCode ^ algo.hashCode ^ cardIdents.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshKeyDetails &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          algo == other.algo &&
          cardIdents == other.cardIdents;
}

/// One subkey inside an OpenPGP cert — role + algorithm + SSH key for display.
class SubkeyInfo {
  /// Human-readable role string: "certify", "sign", "auth", "encrypt",
  /// "certify+sign", or combinations thereof.
  final String role;

  /// Algorithm name from OpenPGP, e.g. "RSA4096", "EdDSA", "ECDH".
  final String algo;

  /// OpenSSH `authorized_keys` line for this subkey, or `None` when the
  /// algorithm has no SSH equivalent (e.g. ECDH encryption keys).
  final String? opensshKey;

  const SubkeyInfo({required this.role, required this.algo, this.opensshKey});

  @override
  int get hashCode => role.hashCode ^ algo.hashCode ^ opensshKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubkeyInfo &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          algo == other.algo &&
          opensshKey == other.opensshKey;
}
